const VER='v3.2.2 Split Build QA',KEY='workforge.project.v2',SCHEMA=322;
const P=['Dashboard','Procedures','Jobs','Packets','Labels','Queue','Assets','Parts & Tools','Actions','Signoffs','Reports','Archive','Diagnostics','Settings'];
let page='Dashboard',sel=0,db;
const $=x=>document.getElementById(x),D=()=>new Date().toISOString().slice(0,10),E=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function sample(){let d=D();return{schema:SCHEMA,c:{job:2,proc:2,label:2,asset:2,item:3,act:2,sig:2},jobs:[{id:'WF-2026-0001',title:'Replace bearing on EF-2',status:'In Progress',due:d,assigned:'M.B. Parks',asset:'EF-2',proc:'PROC-001',procSnapshot:{id:'PROC-001',title:'Replace Small Fan Bearing',rev:1},parts:['6204-2RS Bearing'],tools:['Bearing Puller Kit'],exceptions:'Belt guard screws mismatched.',closeout:'',steps:[{t:'Verify asset',type:'Inspection',done:false,result:'Not Checked',initials:''},{t:'Pull bearing',type:'Work',done:false,result:'Not Checked',initials:''},{t:'Test run',type:'Measurement',done:false,result:'Not Checked',initials:''}]}],procedures:[{id:'PROC-001',title:'Replace Small Fan Bearing',status:'Released',rev:1,revisions:[],steps:[{t:'Verify asset',type:'Inspection',parts:'',tools:'',evidence:'Initials',hold:false},{t:'Pull bearing',type:'Work',parts:'6204-2RS Bearing',tools:'Bearing Puller Kit',evidence:'',hold:true},{t:'Test run',type:'Measurement',parts:'',tools:'',evidence:'Run current / noise check',hold:true}]}],assets:[{id:'AST-001',tag:'EF-2',name:'Roof Exhaust Fan EF-2',loc:'Cumberland Hall / Roof'}],items:[{id:'ITM-001',name:'6204-2RS Bearing',kind:'Part',qty:8},{id:'ITM-002',name:'Bearing Puller Kit',kind:'Tool',qty:1}],labels:[{id:'LBL-001',title:'WF-2026-0001',type:'Job Traveler',payload:'workforge://job/WF-2026-0001',size:'2x1',copies:1}],queue:['LBL-001'],actions:[],signoffs:[],archive:[],log:[]}}
function step(s){return typeof s=='string'?{t:s,type:'Work',parts:'',tools:'',evidence:'',hold:false,done:false,result:'Not Checked',initials:''}:{t:s.t||'Untitled step',type:s.type||'Work',parts:s.parts||'',tools:s.tools||'',evidence:s.evidence||'',hold:!!s.hold,done:!!s.done,result:s.result||'Not Checked',initials:s.initials||''}}
function snap(p){return JSON.parse(JSON.stringify({id:p.id,title:p.title,rev:p.rev||1,status:p.status,steps:(p.steps||[]).map(step)}))}
function norm(x){x=x||sample();['jobs','procedures','assets','items','labels','queue','actions','signoffs','archive','log'].forEach(k=>x[k]=Array.isArray(x[k])?x[k]:[]);x.c=x.c||{};x.procedures.forEach(p=>{p.rev=p.rev||1;p.status=p.status||'Draft';p.revisions=Array.isArray(p.revisions)?p.revisions:[];p.steps=(p.steps||[]).map(step)});x.jobs.forEach(j=>{j.steps=(j.steps||[]).map(step);j.parts=Array.isArray(j.parts)?j.parts:[];j.tools=Array.isArray(j.tools)?j.tools:[];j.status=j.status||'Draft';j.due=j.due||D();j.exceptions=j.exceptions||'';j.closeout=j.closeout||'';if(j.proc&&!j.procSnapshot){let p=x.procedures.find(p=>p.id==j.proc);if(p)j.procSnapshot=snap(p)}});x.labels.forEach(l=>{l.type=l.type||'Custom';l.payload=l.payload||'workforge://label/'+l.id;l.size=l.size||'2x1';l.copies=+l.copies||1});x.queue=x.queue.filter(id=>x.labels.some(l=>l.id==id));x.schema=SCHEMA;return x}
function nid(k){let p={job:'WF-'+new Date().getFullYear()+'-',proc:'PROC-',label:'LBL-',asset:'AST-',item:'ITM-',act:'CA-',sig:'SO-'}[k],n=db.c[k]||1;db.c[k]=n+1;return p+String(n).padStart(k=='job'?4:3,'0')}
function load(){try{return norm(JSON.parse(localStorage.getItem(KEY))||sample())}catch{return norm(sample())}}
function save(){db.version=VER;db.schema=SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()}
function log(a,r=''){db.log.unshift({at:new Date().toISOString(),event:a,ref:r});db.log=db.log.slice(0,80)}
function pct(j){return j.steps.length?Math.round(j.steps.filter(s=>s.done).length*100/j.steps.length):0}
function fail(j){return j.steps.filter(s=>s.result=='Fail').length}
function acts(j){return db.actions.filter(a=>a.source==j.id&&a.status!='Closed').length}
function sigs(j){return db.signoffs.filter(s=>s.source==j.id&&s.status!='Signed').length}
function closeout(j){if(fail(j))return'Blocked: Failed Step';if(acts(j))return'Corrective Action Open';if(sigs(j))return'Signoff Required';if(pct(j)<100)return'Gate Open';if(!j.closeout)return'Closeout Note Needed';return'Ready to Archive'}
function m(t,v){return`<div class=card><div class=metric>${v}</div><b>${t}</b></div>`}
function tbl(h,r){return`<table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${r.map(a=>`<tr>${a.map(x=>`<td>${E(x)}</td>`).join('')}</tr>`).join('')}</table>`}
function card(t,b,x){return`<div class=card><div class=top><h3>${t}</h3><div class=tools>${b}</div></div>${x}</div>`}
function go(p){page=p;draw()}
function draw(){$('ver').textContent=VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()}
function jr(j,i){return`<div class=row onclick='sel=${i};go("Jobs")'><div><b>${E(j.title)}</b><div class=muted>${j.id} · ${j.status} · ${closeout(j)}</div></div><span class=pill>${pct(j)}%</span></div>`}
let views={
Dashboard:()=>`<div class=grid>${m('Active Jobs',db.jobs.length)}${m('Procedures',db.procedures.length)}${m('Labels',db.labels.length)}${m('Queue',db.queue.length)}</div>${db.jobs.map(jr).join('')}`,
Procedures:()=>card('Procedure Composer',`<button class=soft onclick=newProc()>New Procedure</button><button class=ghost onclick=csvProcedures()>Procedures CSV</button>`,db.procedures.map(procCard).join('')),
Jobs:()=>jobView(db.jobs[sel]||db.jobs[0]),
Packets:()=>packetView(),
Labels:()=>card('Labels',`<button class=soft onclick=newLabel()>New Label</button><button class=ghost onclick=batchLabels()>Batch Labels</button><button class=ghost onclick=dedupeLabels()>Dedupe</button><button class=ghost onclick=queueAllLabels()>Queue All</button><button class=ghost onclick=csvLabels()>Labels CSV</button>`,db.labels.map(labelCard).join('')||'<p class=muted>No labels.</p>'),
Queue:()=>card('Label Queue',`<button class=soft onclick=printLabels()>Print Label Sheet</button><button class=ghost onclick=clearQueue()>Clear Queue</button>`,queueView()),
Assets:()=>card('Assets',`<button class=soft onclick=newAsset()>New Asset</button>`,db.assets.map((a,i)=>`<div class=step><b>${E(a.tag)}</b><br>${E(a.name)}<br>${E(a.loc||'')} <button class=ghost onclick='assetLabel(${i})'>Label</button></div>`).join('')),
'Parts & Tools':()=>card('Parts & Tools',`<button class=soft onclick=newItem()>New Item</button>`,db.items.map((it,i)=>`<div class=step><b>${E(it.name)}</b><br>${E(it.kind)} · Qty ${E(it.qty)} <button class=ghost onclick='itemLabel(${i})'>Label</button></div>`).join('')),
Actions:()=>card('Corrective Actions',`<button class=soft onclick=newAction()>New Action</button>`,tbl(['Status','ID','Source','Title','Owner','Due'],db.actions.map(a=>[a.status,a.id,a.source,a.title,a.owner,a.due]))+db.actions.map((a,i)=>`<button class=ghost onclick='closeAction(${i})'>Close ${E(a.id)}</button>`).join(' ')),
Signoffs:()=>card('Signoffs',`<button class=soft onclick=newSignoff()>New Signoff</button>`,tbl(['Status','ID','Source','Role','Reviewer','Date'],db.signoffs.map(s=>[s.status,s.id,s.source,s.role,s.reviewer,s.date]))+db.signoffs.map((s,i)=>`<button class=ghost onclick='signOff(${i})'>Sign ${E(s.id)}</button>`).join(' ')),
Reports:()=>card('Reports',`<button class=ghost onclick=csvStatus()>Status CSV</button><button class=ghost onclick=csvPackets()>Packet CSV</button><button class=ghost onclick=csvProcedures()>Procedures CSV</button><button class=ghost onclick=csvLabels()>Labels CSV</button>`,tbl(['ID','Title','Status','Complete','Closeout'],db.jobs.concat(db.archive).map(j=>[j.id,j.title,j.status,pct(j)+'%',closeout(j)]))),
Archive:()=>card('Archive','',db.archive.map((j,i)=>`<div class=row><b>${E(j.id)} ${E(j.title)}</b><button class=ghost onclick=restore(${i})>Restore</button><button class=ghost onclick='printPacket(db.archive[${i}])'>Print Packet</button></div>`).join('')||'<p class=muted>No archived records.</p>'),
Diagnostics:()=>diagnosticsView(),
Settings:()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Diagnostics')>Open Diagnostics</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${VER}</b></p><p>Schema ${SCHEMA}</p><p class=muted>Use Diagnostics to validate the split build, QR renderer, navigation, and core workflows.</p>`)};
function procCard(p,i){return`<div class=step><b>${E(p.title)}</b><br>${E(p.id)} · Rev ${E(p.rev)} · ${E(p.status)} · ${p.steps.length} steps<div class=tools><button class=ghost onclick='travelerFromProc(${i})'>Create Traveler</button><button class=ghost onclick='cloneProc(${i})'>Clone</button><button class=ghost onclick='revProc(${i})'>Revise</button><button class=ghost onclick='releaseProc(${i})'>Release/Draft</button><button class=ghost onclick='addProcStep(${i})'>Add Step</button></div>${tbl(['#','Type','Step','Parts','Tools','Evidence','Hold'],p.steps.map((s,n)=>[n+1,s.type,s.t,s.parts,s.tools,s.evidence,s.hold?'YES':'']))}<p class=muted>Revision history entries: ${(p.revisions||[]).length}</p></div>`}
function labelCard(l,i){return`<div class=step><div class=label>${wfQrSvg(l.payload)}<div><b>${E(l.title)}</b><br>${E(l.type)} · ${E(l.size)} · copies ${E(l.copies)}<br><span class=muted>${E(l.payload)}</span><div class=tools><button class=ghost onclick='queueLabel(${i})'>Queue</button><button class=ghost onclick='setLabelSize(${i})'>Size</button><button class=ghost onclick='copyLabel(${i})'>Copy</button></div></div></div></div>`}
function queueLabel(i){let id=db.labels[i].id;if(!db.queue.includes(id))db.queue.push(id);save();draw()}
function queueAllLabels(){db.labels.forEach(l=>{if(!db.queue.includes(l.id))db.queue.push(l.id)});save();go('Queue')}
function queueView(){let labs=db.queue.map(id=>db.labels.find(l=>l.id==id)).filter(Boolean);return labs.length?`<div class=sheet>${labs.map(l=>labelCard(l,db.labels.indexOf(l))).join('')}</div>`:'<p class=muted>No labels queued.</p>'}
function printLabels(){let labs=db.queue.map(id=>db.labels.find(l=>l.id==id)).filter(Boolean);if(!labs.length)return alert('No labels queued.');let w=open('','_blank');if(!w)return alert('Allow pop-ups.');w.document.write(`<link rel="stylesheet" href="style.css?v=3.2.2"><div class=sheet>${labs.map(l=>labelCard(l,db.labels.indexOf(l))).join('')}</div>`);w.document.close();w.print&&w.print()}
function clearQueue(){db.queue=[];save();draw()}
function setLabelSize(i){db.labels[i].size=db.labels[i].size=='2x1'?'1x1':'2x1';save();draw()}
function copyLabel(i){db.labels[i].copies=(+db.labels[i].copies||1)+1;queueLabel(i)}
function dedupeLabels(){let s={},out=[];db.labels.forEach(l=>{let k=l.type+'|'+l.payload;if(!s[k]){s[k]=1;out.push(l)}});db.labels=out;db.queue=db.queue.filter(id=>db.labels.some(l=>l.id==id));save();draw()}
function packetView(){let j=db.jobs[sel]||db.jobs[0];return card('Traveler Packets',`<button class=soft onclick='printPacket(db.jobs[sel]||db.jobs[0])'>Print Selected Packet</button><button class=ghost onclick=csvPackets()>Packet CSV</button>`,packetHTML(j))}
function packetHTML(j){if(!j)return'<p>No job selected.</p>';let A=db.actions.filter(a=>a.source==j.id),S=db.signoffs.filter(s=>s.source==j.id),ps=j.procSnapshot;return`<div class=card><h2>${E(j.id)} · ${E(j.title)}</h2><p><b>Status:</b> ${E(j.status)} · <b>Due:</b> ${E(j.due)} · <b>Closeout:</b> ${E(closeout(j))}</p><p><b>Procedure Snapshot:</b> ${ps?E(ps.id+' Rev '+ps.rev+' · '+ps.title):E(j.proc||'')}</p><h3>Work Steps</h3>${j.steps.map((s,i)=>`<div class=step><b>${i+1}. [${E(s.type)}] ${E(s.t)}</b><br>Done: ${s.done?'Yes':'No'} · Result: ${E(s.result)} · Initials: ${E(s.initials||'_____')} · Evidence: ${E(s.evidence||'')}</div>`).join('')}<h3>Corrective Actions</h3>${A.length?tbl(['ID','Title','Owner','Due','Status'],A.map(a=>[a.id,a.title,a.owner,a.due,a.status])):'<p>None recorded.</p>'}<h3>Signoffs</h3>${S.length?tbl(['Role','Reviewer','Status','Date'],S.map(s=>[s.role,s.reviewer,s.status,s.date])):'<p>No signoffs assigned.</p>'}</div>`}
function printPacket(j){let w=open('','_blank');if(!w)return alert('Allow pop-ups.');w.document.write(`<link rel="stylesheet" href="style.css?v=3.2.2">${packetHTML(j)}`);w.document.close();w.print&&w.print();log('Traveler packet printed',j.id);save()}
function jobView(j){return card(j.title,`<button onclick=status('Ready')>Ready</button><button onclick=status('In Progress')>Start</button><button onclick=status('Hold')>Hold</button><button class=soft onclick=archiveJob()>Archive</button><button class=ghost onclick='printPacket(db.jobs[sel])'>Print Packet</button><button class=ghost onclick=actionForJob()>Add Action</button><button class=ghost onclick=signoffForJob()>Add Signoff</button><button class=ghost onclick=labelForJob()>Label</button>`,`<p><span class=pill>${closeout(j)}</span> ${j.procSnapshot?`<span class=pill>Snapshot ${E(j.procSnapshot.id)} Rev ${E(j.procSnapshot.rev)}</span>`:''}</p><label>Title<input value='${E(j.title)}' oninput='j.title=this.value;save()'></label><label>Exception<textarea oninput='j.exceptions=this.value;save()'>${E(j.exceptions)}</textarea></label><label>Closeout Notes<textarea oninput='j.closeout=this.value;save()'>${E(j.closeout)}</textarea></label>${j.steps.map((s,i)=>`<div class=step><b>${i+1}. [${E(s.type)}] ${E(s.t)}</b><label><input type=checkbox ${s.done?'checked':''} onchange='s.done=this.checked;save();draw()'> Done</label><select onchange='s.result=this.value;save();draw()'>${['Not Checked','Pass','Fail','N/A'].map(x=>`<option ${s.result==x?'selected':''}>${x}</option>`).join('')}</select><input placeholder=Initials value='${E(s.initials)}' oninput='s.initials=this.value;save()'></div>`).join('')}`)}
function addLabel(title,type,payload,size='2x1'){let old=db.labels.find(l=>l.payload==payload&&l.type==type);if(old)return old.id;let id=nid('label');db.labels.unshift({id,title,type,payload,size,copies:1});return id}
function status(s){db.jobs[sel].status=s;log('Status changed',db.jobs[sel].id);save();draw()}
function archiveJob(){let j=db.jobs[sel];if(closeout(j)!='Ready to Archive'&&!confirm('Closeout gate open. Archive anyway?'))return;j.status='Complete';db.archive.unshift(j);db.jobs.splice(sel,1);sel=0;save();draw()}
function restore(i){db.jobs.unshift(db.archive.splice(i,1)[0]);go('Jobs');save();draw()}
function newJob(){db.jobs.unshift({id:nid('job'),title:'Untitled Work Traveler',status:'Draft',due:D(),assigned:'',parts:[],tools:[],exceptions:'',closeout:'',steps:[step('New step')]});sel=0;go('Jobs');save();draw()}
function newProc(){db.procedures.unshift({id:nid('proc'),title:'New Procedure',status:'Draft',rev:1,revisions:[],steps:[step('New step')]});save();draw()}
function travelerFromProc(i){let p=db.procedures[i];newJob();let j=db.jobs[0];j.title=p.title;j.proc=p.id;j.procRev=p.rev||1;j.procSnapshot=snap(p);j.steps=(p.steps||[]).map(s=>({...step(s),done:false,result:'Not Checked',initials:''}));j.parts=[...new Set(j.steps.flatMap(s=>(s.parts||'').split(/, */).filter(Boolean)))];j.tools=[...new Set(j.steps.flatMap(s=>(s.tools||'').split(/, */).filter(Boolean)))];log('Traveler created from procedure',p.id+' Rev '+(p.rev||1));save();draw()}
function cloneProc(i){let p=db.procedures[i],q=JSON.parse(JSON.stringify(p));q.id=nid('proc');q.title=p.title+' Copy';q.status='Draft';q.rev=1;q.revisions=[];db.procedures.unshift(q);save();draw()}
function releaseProc(i){let p=db.procedures[i];p.status=p.status=='Released'?'Draft':'Released';log('Procedure status changed',p.id+' '+p.status);save();draw()}
function revProc(i){let p=db.procedures[i];p.revisions=p.revisions||[];p.revisions.unshift({rev:p.rev||1,date:D(),snapshot:snap(p)});p.rev=(p.rev||1)+1;p.status='Draft';log('Procedure revised',p.id+' Rev '+p.rev);save();draw()}
function addProcStep(i){let p=db.procedures[i],t=prompt('Step text','New step');if(!t)return;let type=prompt('Step type','Work')||'Work';p.steps.push({t,type,parts:'',tools:'',evidence:'',hold:/hold/i.test(type)});save();draw()}
function newLabel(){addLabel('New Label','Custom','workforge://label/'+Date.now());save();draw()}
function labelForJob(){let j=db.jobs[sel];addLabel(j.id,'Job Traveler','workforge://job/'+j.id);go('Labels');save();draw()}
function batchLabels(){db.jobs.forEach(j=>addLabel(j.id,'Job Traveler','workforge://job/'+j.id));db.assets.forEach(a=>addLabel(a.tag,'Asset Sticker','workforge://asset/'+a.id));db.items.forEach(i=>addLabel(i.name,i.kind=='Part'?'Part Bin':'Tool Tag','workforge://item/'+i.id));save();draw()}
function newAsset(){db.assets.unshift({id:nid('asset'),tag:'NEW',name:'New Asset',loc:''});save();draw()}
function newItem(){db.items.unshift({id:nid('item'),name:'New Item',kind:'Tool',qty:1});save();draw()}
function assetLabel(i){let a=db.assets[i];addLabel(a.tag,'Asset Sticker','workforge://asset/'+a.id);go('Labels');save();draw()}
function itemLabel(i){let it=db.items[i];addLabel(it.name,it.kind=='Part'?'Part Bin':'Tool Tag','workforge://item/'+it.id);go('Labels');save();draw()}
function newAction(){db.actions.unshift({id:nid('act'),source:'Manual',title:'New corrective action',owner:'',due:D(),status:'Open'});save();draw()}
function actionForJob(){let j=db.jobs[sel];db.actions.unshift({id:nid('act'),source:j.id,title:'Follow up: '+j.title,owner:j.assigned||'',due:D(),status:'Open'});go('Actions');save();draw()}
function closeAction(i){db.actions[i].status='Closed';log('Action closed',db.actions[i].id);save();draw()}
function newSignoff(){db.signoffs.unshift({id:nid('sig'),source:'Manual',role:'Review',reviewer:'',status:'Pending',date:''});save();draw()}
function signoffForJob(){let j=db.jobs[sel];db.signoffs.unshift({id:nid('sig'),source:j.id,role:'Work Review',reviewer:j.assigned||'',status:'Pending',date:''});go('Signoffs');save();draw()}
function signOff(i){db.signoffs[i].status='Signed';db.signoffs[i].date=D();log('Signoff signed',db.signoffs[i].id);save();draw()}
function csv(n,r){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([r.map(x=>x.join(',')).join(String.fromCharCode(10))],{type:'text/csv'}));a.download=n;a.click()}
function csvProcedures(){csv('workforge-procedures.csv',[['ID','Title','Status','Rev','Steps','Revision History'],...db.procedures.map(p=>[p.id,p.title,p.status,p.rev||1,p.steps.length,(p.revisions||[]).length])])}
function csvStatus(){csv('workforge-status.csv',[['ID','Title','Status','Closeout'],...db.jobs.map(j=>[j.id,j.title,j.status,closeout(j)])])}
function csvActions(){csv('workforge-actions.csv',[['Status','ID','Source','Title','Owner','Due'],...db.actions.map(a=>[a.status,a.id,a.source,a.title,a.owner,a.due])])}
function csvSignoffs(){csv('workforge-signoffs.csv',[['Status','ID','Source','Role','Reviewer','Date'],...db.signoffs.map(s=>[s.status,s.id,s.source,s.role,s.reviewer,s.date])])}
function csvLabels(){csv('workforge-labels.csv',[['ID','Title','Type','Size','Copies','Payload'],...db.labels.map(l=>[l.id,l.title,l.type,l.size,l.copies,l.payload])])}
function csvPackets(){csv('workforge-packet-index.csv',[['ID','Title','Status','Due','Closeout','Actions','Signoffs'],...db.jobs.map(j=>[j.id,j.title,j.status,j.due,closeout(j),acts(j),sigs(j)])])}
function exportJSON(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='workforge-backup-'+D()+'.json';a.click()}
function importJSON(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{db=norm(JSON.parse(r.result));log('JSON imported','schema '+SCHEMA);save();draw()};r.readAsText(f)}
function loadSample(){if(confirm('Replace current local data?')){db=norm(sample());save();draw()}}
function clearStore(){if(confirm('Clear local storage?')){localStorage.removeItem(KEY);db=norm(sample());save();draw()}}
function qaChecks(){let out=[],pass=(name,ok,detail='')=>out.push([ok?'PASS':'FAIL',name,detail]);pass('Version visible',VER==='v3.2.2 Split Build QA',VER);pass('Schema migrated',db.schema===SCHEMA,'schema '+db.schema);pass('All nav pages have views',P.every(p=>typeof views[p]=='function'),P.length+' pages');pass('Nav mount exists',!!$('nav'),'#nav');pass('View mount exists',!!$('view'),'#view');pass('Import control exists',!!$('imp'),'#imp');pass('New Traveler above nav',document.querySelector('aside button.soft')&&document.querySelector('aside button.soft').compareDocumentPosition($('nav'))&Node.DOCUMENT_POSITION_FOLLOWING,'layout');pass('Cache-busted app.js',!!document.querySelector('script[src*="app.js?v=3.2.2"]'),'script tag');pass('Cache-busted qr.js',!!document.querySelector('script[src*="qr.js?v=3.2.2"]'),'script tag');pass('Cache-busted style.css',!!document.querySelector('link[href*="style.css?v=3.2.2"]'),'link tag');pass('QR function loaded',typeof wfQrSvg=='function','qr.js');let q='';try{q=wfQrSvg('workforge://job/WF-2026-0001')}catch(e){q=e.message}pass('QR renders SVG',String(q).includes('<svg')&&String(q).includes('<path'),String(q).slice(0,24));pass('Labels exist',db.labels.length>0,db.labels.length+' labels');pass('Queue valid',db.queue.every(id=>db.labels.some(l=>l.id==id)),db.queue.length+' queued');pass('Procedure snapshots present',db.jobs.every(j=>!j.proc||j.procSnapshot),db.jobs.filter(j=>j.procSnapshot).length+' snapshots');pass('Procedure step types present',db.procedures.every(p=>(p.steps||[]).every(s=>s.type)),db.procedures.length+' procedures');pass('Local storage available',(()=>{try{localStorage.setItem('wf_diag','1');localStorage.removeItem('wf_diag');return true}catch{return false}})(),'localStorage');pass('Dark mode toggle available',!!document.querySelector('button[onclick*="dark"]'),'top bar');P.forEach(p=>{try{let html=views[p]();pass('Render '+p,typeof html=='string'&&html.length>0,html.length+' chars')}catch(e){pass('Render '+p,false,e.message)}});return out}
function diagnosticsView(){let rows=qaChecks(),ok=rows.filter(r=>r[0]=='PASS').length,fail=rows.length-ok;return card('Split Build Diagnostics',`<button class=soft onclick='go("Diagnostics")'>Run Diagnostics</button><button class=ghost onclick=exportJSON()>Backup JSON</button>`,`<div class=grid>${m('Checks',rows.length)}${m('Pass',ok)}${m('Fail',fail)}${m('Version','3.2.2')}</div>${tbl(['Result','Check','Detail'],rows)}<p class=muted>These checks validate the split file loading, navigation, QR renderer, procedure snapshots, label queue, and core render paths without mutating project data.</p>`)}
function diag(){go('Diagnostics')}
db=load();draw();
