const WF33_VER='v3.3 Assets, Parts & Tools Depth',WF33_SCHEMA=330;
(function(){
function splitList(v){return Array.isArray(v)?v.filter(Boolean):String(v||'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)}
function wf33Sample(){let d=D();return{schema:WF33_SCHEMA,c:{job:2,proc:2,label:2,asset:2,item:4,act:2,sig:2},jobs:[{id:'WF-2026-0001',title:'Replace bearing on EF-2',status:'In Progress',due:d,assigned:'M.B. Parks',asset:'EF-2',proc:'PROC-001',procSnapshot:{id:'PROC-001',title:'Replace Small Fan Bearing',rev:1},parts:['6204-2RS Bearing'],tools:['Bearing Puller Kit'],exceptions:'Belt guard screws mismatched.',closeout:'',steps:[{t:'Verify asset',type:'Inspection',parts:'',tools:'',evidence:'Initials',hold:false,done:false,result:'Not Checked',initials:''},{t:'Pull bearing',type:'Work',parts:'6204-2RS Bearing',tools:'Bearing Puller Kit',evidence:'',hold:true,done:false,result:'Not Checked',initials:''},{t:'Test run',type:'Measurement',parts:'',tools:'Clamp Meter',evidence:'Run current / noise check',hold:true,done:false,result:'Not Checked',initials:''}]}],procedures:[{id:'PROC-001',title:'Replace Small Fan Bearing',status:'Released',rev:1,revisions:[],steps:[{t:'Verify asset',type:'Inspection',parts:'',tools:'',evidence:'Initials',hold:false},{t:'Pull bearing',type:'Work',parts:'6204-2RS Bearing',tools:'Bearing Puller Kit',evidence:'',hold:true},{t:'Test run',type:'Measurement',parts:'',tools:'Clamp Meter',evidence:'Run current / noise check',hold:true}]}],assets:[{id:'AST-001',tag:'EF-2',name:'Roof Exhaust Fan EF-2',loc:'Cumberland Hall / Roof',criticality:'Medium',notes:'Recurring bearing noise after long summer runs.'}],items:[{id:'ITM-001',name:'6204-2RS Bearing',kind:'Part',qty:8,min:3,loc:'Bin B-14',condition:'Available',howUrl:'',notes:'Standard fan bearing.'},{id:'ITM-002',name:'Bearing Puller Kit',kind:'Tool',qty:1,min:1,loc:'Tool Board A',condition:'Available',howUrl:'https://example.com/bearing-puller',notes:'Inspect jaws before use.'},{id:'ITM-003',name:'Clamp Meter',kind:'Tool',qty:0,min:1,loc:'Electrical Cart',condition:'Missing',howUrl:'',notes:'Sample missing tool to demonstrate kitting gaps.'}],labels:[{id:'LBL-001',title:'WF-2026-0001',type:'Job Traveler',payload:'workforge://job/WF-2026-0001',size:'2x1',copies:1}],queue:['LBL-001'],actions:[],signoffs:[],archive:[],log:[]}}
function wf33Norm(x){x=norm(x||wf33Sample());x.schema=WF33_SCHEMA;x.assets.forEach(a=>{a.loc=a.loc||'';a.criticality=a.criticality||'Normal';a.notes=a.notes||''});x.items.forEach(i=>{i.kind=i.kind||'Tool';i.qty=Number(i.qty||0);i.min=Number(i.min||0);i.loc=i.loc||'';i.condition=i.condition||'Available';i.howUrl=i.howUrl||'';i.notes=i.notes||''});x.jobs.forEach(j=>{j.parts=splitList(j.parts);j.tools=splitList(j.tools);j.asset=j.asset||''});return x}
sample=wf33Sample;norm=wf33Norm;save=function(){db.version=WF33_VER;db.schema=WF33_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
function allJobs(){return db.jobs.concat(db.archive)}
function matchAsset(a,j){return [a.id,a.tag,a.name].filter(Boolean).includes(j.asset)}
function assetJobs(a){return allJobs().filter(j=>matchAsset(a,j))}
function itemMatch(name,kind){let q=String(name||'').toLowerCase();return db.items.find(i=>(!kind||i.kind==kind)&&[i.name,i.id].some(v=>String(v||'').toLowerCase()==q))}
function reqParts(j){return [...new Set([...(j.parts||[]),...j.steps.flatMap(s=>splitList(s.parts))])].filter(Boolean)}
function reqTools(j){return [...new Set([...(j.tools||[]),...j.steps.flatMap(s=>splitList(s.tools))])].filter(Boolean)}
function missingParts(j){return reqParts(j).filter(n=>{let i=itemMatch(n,'Part');return !i||Number(i.qty)<=0})}
function missingTools(j){return reqTools(j).filter(n=>{let i=itemMatch(n,'Tool');return !i||Number(i.qty)<=0||!/available/i.test(i.condition)})}
function kitStatus(j){let r=reqParts(j).length+reqTools(j).length;return missingParts(j).length||missingTools(j).length?'Missing':r?'Ready':'Not Checked'}
function lowParts(){return db.items.filter(i=>i.kind=='Part'&&Number(i.qty)<=Number(i.min||0))}
function toolIssues(){return db.items.filter(i=>i.kind=='Tool'&&(!/available/i.test(i.condition)||Number(i.qty)<=0))}
function kitGaps(){return db.jobs.filter(j=>kitStatus(j)=='Missing')}
window.reqParts=reqParts;window.reqTools=reqTools;window.missingParts=missingParts;window.missingTools=missingTools;window.kitStatus=kitStatus;
if(!P.includes('Kitting'))P.splice(P.indexOf('Parts & Tools')+1,0,'Kitting');
views.Dashboard=()=>`<div class=grid>${m('Assets',db.assets.length)}${m('Low Stock',lowParts().length)}${m('Tool Issues',toolIssues().length)}${m('Kitting Gaps',kitGaps().length)}</div>${db.jobs.map((j,i)=>`<div class=row onclick='sel=${i};go("Jobs")'><div><b>${E(j.title)}</b><div class=muted>${j.id} · ${j.status} · ${closeout(j)} · Kit ${kitStatus(j)}</div></div><span class=pill>${pct(j)}%</span></div>`).join('')}`;
views.Assets=()=>card('Assets',`<button class=soft onclick=newAsset()>New Asset</button><button class=ghost onclick=csvAssets()>Assets CSV</button>`,db.assets.map(assetCard).join('')||'<p class=muted>No assets.</p>');
views['Parts & Tools']=()=>partsToolsView();
views.Kitting=()=>card('Traveler Kitting',`<button class=soft onclick=holdMissingKits()>Hold Missing Kits</button><button class=ghost onclick=csvKitting()>Kitting CSV</button>`,tbl(['Kit','ID','Title','Required Parts','Missing Parts','Required Tools','Missing Tools'],db.jobs.map(j=>[kitStatus(j),j.id,j.title,reqParts(j).join(', '),missingParts(j).join(', '),reqTools(j).join(', '),missingTools(j).join(', ')])));
views.Reports=()=>card('Reports',`<button class=ghost onclick=csvStatus()>Status CSV</button><button class=ghost onclick=csvKitting()>Kitting CSV</button><button class=ghost onclick=csvAssets()>Assets CSV</button><button class=ghost onclick=csvParts()>Parts CSV</button><button class=ghost onclick=csvTools()>Tools CSV</button>`,tbl(['Asset','Open Jobs','History','Failed Steps'],db.assets.map(a=>[a.tag,assetJobs(a).filter(j=>db.jobs.includes(j)).length,assetJobs(a).length,assetJobs(a).reduce((n,j)=>n+fail(j),0)]))+tbl(['Low Part','Qty','Min','Location'],lowParts().map(i=>[i.name,i.qty,i.min,i.loc]))+tbl(['Tool Issue','Condition','Qty','Location'],toolIssues().map(i=>[i.name,i.condition,i.qty,i.loc])));
views.Diagnostics=()=>diagnosticsView();
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Diagnostics')>Open Diagnostics</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF33_VER}</b></p><p>Schema ${WF33_SCHEMA}</p><p class=muted>Use Diagnostics to validate assets, parts, tools, kitting, QR labels, and the split build.</p>`);
function assetCard(a,i){let hist=assetJobs(a);return`<div class=step><div class=top><div><b>${E(a.tag)} · ${E(a.name)}</b><br><span class=muted>${E(a.loc)} · Criticality ${E(a.criticality)}</span></div><div class=tools><button class=ghost onclick='assetLabel(${i})'>Label</button><button class=ghost onclick='assetJob(${i})'>New Job</button></div></div><p>${E(a.notes)}</p>${tbl(['Job','Title','Status','Closeout'],hist.map(j=>[j.id,j.title,j.status,closeout(j)]))}</div>`}
function partsToolsView(){let parts=db.items.filter(i=>i.kind=='Part'),tools=db.items.filter(i=>i.kind=='Tool');return card('Parts Inventory',`<button class=soft onclick=newPart()>New Part</button><button class=ghost onclick=csvParts()>Parts CSV</button>`,tbl(['Status','ID','Part','Qty','Min','Location','Used On'],parts.map(i=>[(Number(i.qty)<=Number(i.min)?'LOW':'OK'),i.id,i.name,i.qty,i.min,i.loc,allJobs().filter(j=>reqParts(j).includes(i.name)).map(j=>j.id).join(', ')])))+card('Tool Records',`<button class=soft onclick=newTool()>New Tool</button><button class=ghost onclick=csvTools()>Tools CSV</button>`,tools.map(t=>`<div class=step><b>${E(t.name)}</b><br>${E(t.id)} · ${E(t.condition)} · Qty ${E(t.qty)} · ${E(t.loc)}${t.howUrl?`<br><a href="${E(t.howUrl)}" target="_blank">How to use</a>`:''}<br><span class=muted>${E(t.notes)}</span><div><button class=ghost onclick='itemLabel(${db.items.indexOf(t)})'>Label</button></div></div>`).join('')||'<p class=muted>No tools.</p>')}
let oldPacketHTML=packetHTML;packetHTML=function(j){let html=oldPacketHTML(j);return html.replace('<h3>Work Steps</h3>',`<h3>Kitting</h3>${tbl(['Required Parts','Missing Parts','Required Tools','Missing Tools'],[[reqParts(j).join(', '),missingParts(j).join(', '),reqTools(j).join(', '),missingTools(j).join(', ')]])}<h3>Work Steps</h3>`)};
let oldJobView=jobView;jobView=function(j){let h=oldJobView(j);return h.replace('</p><label>Title',` <span class=pill>Kit ${kitStatus(j)}</span></p><label>Asset tag or ID<input value='${E(j.asset||'')}' oninput='j.asset=this.value;save();draw()'></label><label>Parts, comma separated<input value='${E((j.parts||[]).join(', '))}' oninput='j.parts=splitList(this.value);save();draw()'></label><label>Tools, comma separated<input value='${E((j.tools||[]).join(', '))}' oninput='j.tools=splitList(this.value);save();draw()'></label>${tbl(['Required Parts','Missing Parts','Required Tools','Missing Tools'],[[reqParts(j).join(', '),missingParts(j).join(', '),reqTools(j).join(', '),missingTools(j).join(', ')]])}<label>Title`)};
window.newAsset=function(){db.assets.unshift({id:nid('asset'),tag:'NEW',name:'New Asset',loc:'',criticality:'Normal',notes:''});save();draw()};
window.assetJob=function(i){let a=db.assets[i];newJob();db.jobs[0].asset=a.tag;db.jobs[0].title='Work on '+a.tag;save();draw()};
window.newPart=function(){db.items.unshift({id:nid('item'),name:'New Part',kind:'Part',qty:0,min:1,loc:'',condition:'Available',howUrl:'',notes:''});save();draw()};
window.newTool=function(){db.items.unshift({id:nid('item'),name:'New Tool',kind:'Tool',qty:1,min:1,loc:'',condition:'Available',howUrl:'',notes:''});save();draw()};
window.newItem=function(){newTool()};
window.holdMissingKits=function(){db.jobs.forEach(j=>{if(kitStatus(j)=='Missing')j.status='Hold'});log('Missing kits placed on hold','Kitting');save();draw()};
window.csvAssets=function(){csv('workforge-assets.csv',[['ID','Tag','Name','Location','Criticality','Open Jobs','History'],...db.assets.map(a=>[a.id,a.tag,a.name,a.loc,a.criticality,assetJobs(a).filter(j=>db.jobs.includes(j)).length,assetJobs(a).length])])};
window.csvParts=function(){csv('workforge-parts.csv',[['ID','Part','Qty','Min','Location','Status'],...db.items.filter(i=>i.kind=='Part').map(i=>[i.id,i.name,i.qty,i.min,i.loc,Number(i.qty)<=Number(i.min)?'LOW':'OK'])])};
window.csvTools=function(){csv('workforge-tools.csv',[['ID','Tool','Qty','Condition','Location','How To Use URL'],...db.items.filter(i=>i.kind=='Tool').map(i=>[i.id,i.name,i.qty,i.condition,i.loc,i.howUrl])])};
window.csvKitting=function(){csv('workforge-kitting.csv',[['Kit','ID','Title','Required Parts','Missing Parts','Required Tools','Missing Tools'],...db.jobs.map(j=>[kitStatus(j),j.id,j.title,reqParts(j).join('; '),missingParts(j).join('; '),reqTools(j).join('; '),missingTools(j).join('; ')])])};
let oldTravelerFromProc=travelerFromProc;travelerFromProc=function(i){oldTravelerFromProc(i);db.jobs[0].parts=[...new Set(db.jobs[0].steps.flatMap(s=>splitList(s.parts)))];db.jobs[0].tools=[...new Set(db.jobs[0].steps.flatMap(s=>splitList(s.tools)))];save();draw()};
let oldNewJob=newJob;newJob=function(){oldNewJob();db.jobs[0].asset=db.jobs[0].asset||'';db.jobs[0].parts=splitList(db.jobs[0].parts);db.jobs[0].tools=splitList(db.jobs[0].tools);save();draw()};
function wf33Checks(){let out=[],pass=(n,ok,d='')=>out.push([ok?'PASS':'FAIL',n,d]);pass('Version visible',WF33_VER.includes('v3.3'),WF33_VER);pass('Schema migrated',db.schema===WF33_SCHEMA,'schema '+db.schema);pass('Kitting page registered',P.includes('Kitting'),'nav');pass('Assets normalized',db.assets.every(a=>a.tag&&a.name),'assets '+db.assets.length);pass('Items normalized',db.items.every(i=>i.kind&&i.condition!==undefined),'items '+db.items.length);pass('Low stock report works',Array.isArray(lowParts()),lowParts().length+' low');pass('Tool issue report works',Array.isArray(toolIssues()),toolIssues().length+' issues');pass('Kitting gaps computed',Array.isArray(kitGaps()),kitGaps().length+' gaps');pass('QR function loaded',typeof wfQrSvg=='function','qr.js');P.forEach(p=>{try{let html=views[p]();pass('Render '+p,typeof html=='string'&&html.length>0,html.length+' chars')}catch(e){pass('Render '+p,false,e.message)}});return out}
function diagnosticsView(){let rows=wf33Checks(),ok=rows.filter(r=>r[0]=='PASS').length,fail=rows.length-ok;return card('Split Build Diagnostics',`<button class=soft onclick='go("Diagnostics")'>Run Diagnostics</button><button class=ghost onclick=exportJSON()>Backup JSON</button>`,`<div class=grid>${m('Checks',rows.length)}${m('Pass',ok)}${m('Fail',fail)}${m('Version','3.3')}</div>${tbl(['Result','Check','Detail'],rows)}<p class=muted>These checks validate assets, parts, tools, kitting, reports, QR rendering, and the split build.</p>`)}
draw=function(){$('ver').textContent=WF33_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db=norm(db);save();draw();
})();
