const WF33_VER='v3.3 Assets, Parts & Tools Depth',WF33_SCHEMA=330;
(function(){
const baseNorm33=norm;
function splitList(v){return Array.isArray(v)?v.filter(Boolean):String(v||'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)}
window.splitList=splitList;
function wf33Sample(){let d=D();return{schema:WF33_SCHEMA,c:{job:2,proc:2,label:2,asset:2,item:4,act:2,sig:2},jobs:[{id:'WF-2026-0001',title:'Replace bearing on EF-2',status:'In Progress',due:d,assigned:'M.B. Parks',asset:'EF-2',proc:'PROC-001',parts:['6204-2RS Bearing'],tools:['Bearing Puller Kit'],exceptions:'',closeout:'',steps:[{t:'Verify asset',type:'Inspection',parts:'',tools:'',evidence:'Initials',hold:false,done:false,result:'Not Checked',initials:''},{t:'Pull bearing',type:'Work',parts:'6204-2RS Bearing',tools:'Bearing Puller Kit',evidence:'',hold:true,done:false,result:'Not Checked',initials:''}]}],procedures:[{id:'PROC-001',title:'Replace Small Fan Bearing',status:'Released',rev:1,revisions:[],steps:[{t:'Verify asset',type:'Inspection',parts:'',tools:'',evidence:'Initials',hold:false},{t:'Pull bearing',type:'Work',parts:'6204-2RS Bearing',tools:'Bearing Puller Kit',evidence:'',hold:true}]}],assets:[{id:'AST-001',tag:'EF-2',name:'Roof Exhaust Fan EF-2',loc:'Cumberland Hall / Roof',criticality:'Medium',notes:'Recurring bearing noise.'}],items:[{id:'ITM-001',name:'6204-2RS Bearing',kind:'Part',qty:8,min:3,loc:'Bin B-14',condition:'Available',howUrl:'',notes:''},{id:'ITM-002',name:'Bearing Puller Kit',kind:'Tool',qty:1,min:1,loc:'Tool Board A',condition:'Available',howUrl:'',notes:''}],labels:[{id:'LBL-001',title:'WF-2026-0001',type:'Job Traveler',payload:'workforge://job/WF-2026-0001',size:'2x1',copies:1}],queue:['LBL-001'],actions:[],signoffs:[],archive:[],log:[]}}
function wf33Norm(x){x=baseNorm33(x||wf33Sample());x.assets=x.assets||[];x.items=x.items||[];x.assets.forEach(a=>{a.loc=a.loc||'';a.criticality=a.criticality||'Normal';a.notes=a.notes||''});x.items.forEach(i=>{i.kind=i.kind||'Tool';i.qty=Number(i.qty||0);i.min=Number(i.min||0);i.loc=i.loc||'';i.condition=i.condition||'Available';i.howUrl=i.howUrl||'';i.notes=i.notes||''});x.jobs.forEach(j=>{j.parts=splitList(j.parts);j.tools=splitList(j.tools);j.asset=j.asset||''});return x}
sample=wf33Sample;norm=wf33Norm;save=function(){db.version=WF33_VER;db.schema=WF33_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
function allJobs(){return db.jobs.concat(db.archive||[])}
function matchAsset(a,j){return [a.id,a.tag,a.name].filter(Boolean).includes(j.asset)}
function assetJobs(a){return allJobs().filter(j=>matchAsset(a,j))}
function itemMatch(name,kind){let q=String(name||'').toLowerCase();return db.items.find(i=>(!kind||i.kind==kind)&&[i.name,i.id].some(v=>String(v||'').toLowerCase()==q))}
function reqParts(j){return [...new Set([...(j.parts||[]),...(j.steps||[]).flatMap(s=>splitList(s.parts))])].filter(Boolean)}
function reqTools(j){return [...new Set([...(j.tools||[]),...(j.steps||[]).flatMap(s=>splitList(s.tools))])].filter(Boolean)}
function missingParts(j){return reqParts(j).filter(n=>{let i=itemMatch(n,'Part');return !i||Number(i.qty)<=0})}
function missingTools(j){return reqTools(j).filter(n=>{let i=itemMatch(n,'Tool');return !i||Number(i.qty)<=0||!/available/i.test(i.condition)})}
function kitStatus(j){let r=reqParts(j).length+reqTools(j).length;return missingParts(j).length||missingTools(j).length?'Missing':r?'Ready':'Not Checked'}
function lowParts(){return db.items.filter(i=>i.kind=='Part'&&Number(i.qty)<=Number(i.min||0))}
function toolIssues(){return db.items.filter(i=>i.kind=='Tool'&&(!/available/i.test(i.condition)||Number(i.qty)<=0))}
window.reqParts=reqParts;window.reqTools=reqTools;window.missingParts=missingParts;window.missingTools=missingTools;window.kitStatus=kitStatus;
if(!P.includes('Kitting'))P.splice(P.indexOf('Parts & Tools')+1,0,'Kitting');
views.Assets=()=>card('Assets',`<button class=soft onclick=newAsset()>New Asset</button><button class=ghost onclick=csvAssets()>Assets CSV</button>`,db.assets.map(assetCard).join('')||'<p class=muted>No assets.</p>');
views['Parts & Tools']=()=>partsToolsView();
views.Kitting=()=>card('Traveler Kitting',`<button class=soft onclick=holdMissingKits()>Hold Missing Kits</button><button class=ghost onclick=csvKitting()>Kitting CSV</button>`,tbl(['Kit','ID','Title','Required Parts','Missing Parts','Required Tools','Missing Tools'],db.jobs.map(j=>[kitStatus(j),j.id,j.title,reqParts(j).join(', '),missingParts(j).join(', '),reqTools(j).join(', '),missingTools(j).join(', ')])));
function assetCard(a,i){let hist=assetJobs(a);return`<div class=step><div class=top><div><b>${E(a.tag)} · ${E(a.name)}</b><br><span class=muted>${E(a.loc)} · Criticality ${E(a.criticality)}</span></div><div class=tools><button class=ghost onclick='assetLabel(${i})'>Label</button><button class=ghost onclick='assetJob(${i})'>New Job</button></div></div><p>${E(a.notes)}</p>${tbl(['Job','Title','Status','Closeout'],hist.map(j=>[j.id,j.title,j.status,closeout(j)]))}</div>`}
function partsToolsView(){let parts=db.items.filter(i=>i.kind=='Part'),tools=db.items.filter(i=>i.kind=='Tool');return card('Parts Inventory',`<button class=soft onclick=newPart()>New Part</button><button class=ghost onclick=csvParts()>Parts CSV</button>`,tbl(['Status','ID','Part','Qty','Min','Location','Used On'],parts.map(i=>[(Number(i.qty)<=Number(i.min)?'LOW':'OK'),i.id,i.name,i.qty,i.min,i.loc,allJobs().filter(j=>reqParts(j).includes(i.name)).map(j=>j.id).join(', ')])))+card('Tool Records',`<button class=soft onclick=newTool()>New Tool</button><button class=ghost onclick=csvTools()>Tools CSV</button>`,tools.map(t=>`<div class=step><b>${E(t.name)}</b><br>${E(t.id)} · ${E(t.condition)} · Qty ${E(t.qty)} · ${E(t.loc)}<br><span class=muted>${E(t.notes)}</span><div><button class=ghost onclick='itemLabel(${db.items.indexOf(t)})'>Label</button></div></div>`).join('')||'<p class=muted>No tools.</p>')}
let oldPacketHTML=packetHTML;packetHTML=function(j){let html=oldPacketHTML(j);return html.replace('<h3>Work Steps</h3>',`<h3>Kitting</h3>${tbl(['Required Parts','Missing Parts','Required Tools','Missing Tools'],[[reqParts(j).join(', '),missingParts(j).join(', '),reqTools(j).join(', '),missingTools(j).join(', ')]])}<h3>Work Steps</h3>`)};
})();
