const WF451_VER='v4.5.1 Control Board Drag & Drop',WF451_SCHEMA=451;
(function(){
const DND_STATES=['Draft','Ready for Kitting','Waiting on Parts','Kitted','Ready to Start','In Progress','Hold','Waiting on Signoff','Complete'];
function dndCss(){if(document.getElementById('wf451-style'))return;let s=document.createElement('style');s.id='wf451-style';s.textContent=`.wf-dnd-board{display:grid;grid-template-columns:repeat(3,minmax(260px,1fr));gap:16px}.wf-drop-lane{min-height:260px;border:1px solid #cdb790;border-radius:18px;background:rgba(255,255,255,.45);padding:16px}.wf-drop-lane.drag-over{outline:4px solid rgba(180,88,0,.25);background:rgba(255,235,198,.65)}.wf-drag-card{cursor:grab;user-select:none}.wf-drag-card:active{cursor:grabbing}.wf-drag-card.dragging{opacity:.5;transform:scale(.98)}.wf-dnd-hint{font-size:12px;opacity:.75;margin-top:8px}.dark .wf-drop-lane{background:rgba(17,24,39,.55);border-color:#4b5563}.dark .wf-drop-lane.drag-over{background:rgba(75,85,99,.65)}@media(max-width:900px){.wf-dnd-board{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function dndKit(j){try{return typeof kitStatus=='function'?kitStatus(j):((j.kit&&j.kit.status)||'Not Checked')}catch{return(j.kit&&j.kit.status)||'Not Checked'}}
function dndReqSigs(j){return(db.signoffs||[]).filter(s=>s.source==j.id&&s.status!='Signed').length}
function dndReqActs(j){return(db.actions||[]).filter(a=>a.source==j.id&&a.status!='Closed').length}
function dndDone(j){return j.steps&&j.steps.length&&j.steps.every(s=>s.done)}
function dndGate(j,target){let k=dndKit(j),errs=[];if(['Kitted','Ready to Start','In Progress'].includes(target)&&!['Ready','Kitted'].includes(k))errs.push('kit is not ready');if(target=='Complete'&&!dndDone(j))errs.push('steps incomplete');if(target=='Complete'&&dndReqActs(j))errs.push('open corrective actions');if(target=='Complete'&&dndReqSigs(j))errs.push('pending signoffs');if(target=='Waiting on Signoff'&&!dndDone(j))errs.push('steps incomplete');return errs}
function dndSetState(i,state){let j=db.jobs[i];if(!j)return;let old=j.status||'Draft',errs=dndGate(j,state);if(errs.length&&!confirm('Gate warning: '+errs.join(', ')+'. Move anyway?'))return false;j.status=state;log('Drag moved traveler',j.id+' from '+old+' to '+state);save();draw();return true}
function dragCard(j,i){return`<div class="step wf-drag-card" draggable="true" data-job-index="${i}" ondragstart="wfDragStart(event)" ondragend="wfDragEnd(event)"><b>${E(j.id)} · ${E(j.title)}</b><br><span class=muted>${E(j.asset||'No asset')} · Due ${E(j.due||'')} · Kit ${E(dndKit(j))} · ${pct(j)}%</span><br><span class=muted>Actions ${dndReqActs(j)} · Signoffs ${dndReqSigs(j)}</span><div class=tools><button class=ghost onclick='sel=${i};go("Jobs")'>Open</button><button class=ghost onclick='quickNext(${i})'>Next</button><button class=ghost onclick='printProductionPacket(${i})'>Packet</button></div><div class=wf-dnd-hint>Drag to another status lane</div></div>`}
function dndBoard(){return`<div class=wf-dnd-board>${DND_STATES.map(st=>`<div class="wf-drop-lane" data-state="${E(st)}" ondragover="wfDragOver(event)" ondragleave="wfDragLeave(event)" ondrop="wfDrop(event)"><h3>${E(st)}</h3>${db.jobs.filter(j=>(j.status||'Draft')==st).map(j=>dragCard(j,db.jobs.indexOf(j))).join('')||'<p class=muted>No travelers.</p>'}</div>`).join('')}</div>`}
views['Control Board']=()=>card('Work Control Board',`<button class=soft onclick=newJob()>New Traveler</button><button class=ghost onclick=go('Schedule')>Schedule</button><button class=ghost onclick=csvBoard()>Board CSV</button>`,`<p class=muted>Drag traveler cards between status lanes. Gate rules still apply when a card is dropped.</p>${dndBoard()}`);
window.wfDragStart=function(ev){let c=ev.currentTarget;ev.dataTransfer.setData('text/plain',c.dataset.jobIndex);ev.dataTransfer.effectAllowed='move';setTimeout(()=>c.classList.add('dragging'),0)};
window.wfDragEnd=function(ev){ev.currentTarget.classList.remove('dragging');document.querySelectorAll('.wf-drop-lane.drag-over').forEach(x=>x.classList.remove('drag-over'))};
window.wfDragOver=function(ev){ev.preventDefault();ev.currentTarget.classList.add('drag-over');ev.dataTransfer.dropEffect='move'};
window.wfDragLeave=function(ev){ev.currentTarget.classList.remove('drag-over')};
window.wfDrop=function(ev){ev.preventDefault();let lane=ev.currentTarget;lane.classList.remove('drag-over');let i=Number(ev.dataTransfer.getData('text/plain')),state=lane.dataset.state;if(Number.isFinite(i)&&state)dndSetState(i,state)};
let oldTest451=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest451?oldTest451():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.5.1 visible',WF451_VER.includes('v4.5.1'),WF451_VER);pass('Control Board DND override installed',String(views['Control Board']()).includes('wf-drop-lane'),'lanes');pass('Drag handlers available',typeof wfDragStart=='function'&&typeof wfDrop=='function','handlers');pass('Gate checks available',typeof dndGate=='function','gates');return html+card('v4.5.1 Control Board Drag & Drop Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
if(window.WF){WF.version=WF451_VER;WF.boardDnd={states:DND_STATES,move:dndSetState,gate:dndGate}}
let oldDraw451=draw;draw=function(){oldDraw451();dndCss();$('ver').textContent=WF451_VER};
save=function(){db.version=WF451_VER;db.schema=WF451_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
dndCss();db.schema=WF451_SCHEMA;save();draw();
})();
