const WF462_VER='v4.6.2 Cleanup + Built-in Fresh Start',WF462_SCHEMA=462;
(function(){
const ORDER=['Control Board','Schedule','Workload','People','Dashboard','Jobs','Procedures','PM Templates','Kitting','Pull Sheets','Inventory Control','Closeout','Assets','Parts & Tools','Reports','Visual Dashboard','Packets','Labels','Queue','Data Exchange','Fresh Start','Mobile / Print','Architecture','Test Harness','Settings'];
const ARRAYS=['jobs','procedures','assets','items','labels','queue','actions','signoffs','archive','log','maintenance','inventoryMoves','people'];
const VALID=['Draft','Ready for Kitting','Waiting on Parts','Kitted','Ready to Start','In Progress','Hold','Waiting on Signoff','Complete','Archived'];
function uniq(a){return[...new Set(a.filter(Boolean))]}
function split46(v){return Array.isArray(v)?v.filter(Boolean):String(v||'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)}
function emptyWorkspace46(){let o={version:WF462_VER,schema:WF462_SCHEMA,createdAt:new Date().toISOString(),workspaceName:'Real Work Forge Workspace'};ARRAYS.forEach(k=>o[k]=[]);return o}
function downloadFreshBackup46(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='workforge-before-fresh-start.json';a.click()}
function startFreshWorkspace46(){if(!confirm('Start fresh and remove all current sample/demo records from this browser?'))return;if(confirm('Download a backup first?'))downloadFreshBackup46();let prefs={dark:localStorage.getItem('workforge.dark'),nav:localStorage.getItem('workforge.navCollapsed')};localStorage.setItem('workforge.lastSafetyCopy',JSON.stringify(db));db=emptyWorkspace46();if(prefs.dark!=null)localStorage.setItem('workforge.dark',prefs.dark);if(prefs.nav!=null)localStorage.setItem('workforge.navCollapsed',prefs.nav);save();page='Control Board';sel=0;draw();alert('Fresh workspace ready. Sample data has been cleared from this browser.')}
function seedRealStarter46(){if(!confirm('Create a minimal real-use starter set with no sample jobs?'))return;db=emptyWorkspace46();db.procedures.push({id:'PROC-001',title:'New Controlled Procedure',rev:1,status:'Draft',steps:[]});db.people.push({id:'PER-001',name:'Unassigned',role:'Placeholder',active:true,notes:'Replace with real people.'});db.log.unshift({t:new Date().toLocaleString(),a:'Starter workspace created',d:'Fresh Start'});save();page='Procedures';draw()}
function freshStats46(){return[['Jobs',db.jobs.length],['Procedures',db.procedures.length],['Assets',db.assets.length],['Parts / Tools',db.items.length],['People',db.people.length],['Labels',db.labels.length],['Archive',db.archive.length],['Inventory Moves',db.inventoryMoves.length]]}
function ensurePeople46(){db.people=Array.isArray(db.people)?db.people:[];let names=new Set(db.people.map(p=>p.name).filter(Boolean));(db.jobs||[]).forEach(j=>{if(j.assigned)names.add(j.assigned)});(db.actions||[]).forEach(a=>{if(a.owner)names.add(a.owner)});(db.signoffs||[]).forEach(s=>{if(s.reviewer)names.add(s.reviewer)});[...names].forEach(n=>{if(!db.people.some(p=>p.name==n))db.people.push({id:'PER-'+String(db.people.length+1).padStart(3,'0'),name:n,role:'Technician',active:true,notes:''})});return db.people}
function close46(j){j.closeoutPack=j.closeoutPack||{};let c=j.closeoutPack;c.asFound=c.asFound||'';c.asLeft=c.asLeft||'';c.summary=c.summary||j.closeout||'';c.labor=c.labor||'';c.evidence=Array.isArray(c.evidence)?c.evidence:[];c.measurements=Array.isArray(c.measurements)?c.measurements:[];c.finalReviewer=c.finalReviewer||'';c.reviewDate=c.reviewDate||'';return c}
function cleanDb46(){ARRAYS.forEach(k=>db[k]=Array.isArray(db[k])?db[k]:[]);db.jobs.forEach(j=>{j.id=j.id||nid('job');j.title=j.title||'Untitled Work Traveler';j.status=VALID.includes(j.status)?j.status:'Draft';j.steps=Array.isArray(j.steps)?j.steps:[];j.parts=split46(j.parts);j.tools=split46(j.tools);j.kit=j.kit||{status:'Not Checked',notes:'',pulledBy:''};close46(j)});db.procedures.forEach(p=>{p.id=p.id||nid('proc');p.title=p.title||'Untitled Procedure';p.steps=Array.isArray(p.steps)?p.steps:[]});db.assets.forEach(a=>{a.id=a.id||a.tag||nid('asset');a.tag=a.tag||a.id;a.name=a.name||a.tag});db.items.forEach(i=>{i.id=i.id||nid('item');i.kind=i.kind||'Part';i.name=i.name||i.id;i.qty=Number(i.qty||0);i.min=Number(i.min||0)});db.labels.forEach(l=>{l.id=l.id||nid('lbl');l.text=l.text||l.id});db.queue=uniq(db.queue).filter(id=>db.labels.some(l=>l.id==id));ensurePeople46();db.schema=WF462_SCHEMA;db.version=WF462_VER;return db}
function systemRows46(){return[['Version',WF462_VER],['Schema',WF462_SCHEMA],['Jobs',db.jobs.length],['Procedures',db.procedures.length],['Assets',db.assets.length],['Parts / Tools',db.items.length],['People',db.people.length],['Labels',db.labels.length],['Queue',db.queue.length],['Archive',db.archive.length]]}
function cleanupChecks46(){let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('Version visible',WF462_VER.includes('v4.6.2'),WF462_VER);pass('Fresh Start page registered',P.includes('Fresh Start'),'nav');pass('Navigation deduplicated',P.length===new Set(P).size,P.length+' pages');pass('Required arrays present',ARRAYS.every(k=>Array.isArray(db[k])),ARRAYS.length+' arrays');pass('Fresh start function built in',typeof window.startFreshWorkspace=='function','visible without extra chain');pass('Label queue valid',db.queue.every(id=>db.labels.some(l=>l.id==id)),db.queue.length+' queued');pass('Jobs normalized',db.jobs.every(j=>j.id&&j.title&&Array.isArray(j.steps)&&Array.isArray(j.parts)&&Array.isArray(j.tools)),db.jobs.length+' jobs');pass('Workflow pages present',['Control Board','Jobs','Kitting','Inventory Control','Closeout','Reports'].every(p=>P.includes(p)),'core flow');return rows}
function nextActions46(){let rows=[];db.jobs.filter(j=>j.status!='Complete').slice(0,8).forEach(j=>{let action='Open traveler';if(j.status=='Draft')action='Review and release';else if(j.status=='Ready for Kitting'||j.status=='Waiting on Parts')action='Kit parts/tools';else if(j.status=='Kitted'||j.status=='Ready to Start')action='Start work';else if(j.status=='In Progress')action='Complete steps';else if(j.status=='Waiting on Signoff')action='Collect signoff';else if(j.status=='Hold')action='Resolve hold';rows.push([action,j.id,j.title,j.status,j.due||'',j.assigned||''])});return rows}
function cleanDashboard46(){let overdue=db.jobs.filter(j=>j.due&&new Date(j.due)<new Date(D())&&j.status!='Complete').length;let open=db.jobs.filter(j=>j.status!='Complete').length;let kit=db.jobs.filter(j=>['Ready for Kitting','Waiting on Parts'].includes(j.status)).length;let close=db.jobs.filter(j=>j.status=='Waiting on Signoff').length;return`<div class=grid>${m('Open Work',open)}${m('Overdue',overdue)}${m('Needs Kitting',kit)}${m('Closeout / Signoff',close)}</div>${card('Next Actions',`<button class=soft onclick=go('Control Board')>Open Control Board</button><button class=ghost onclick=newJob()>New Traveler</button><button class=ghost onclick=go('Fresh Start')>Fresh Start</button><button class=ghost onclick=go('Data Exchange')>Backup / Import</button>`,tbl(['Action','ID','Title','State','Due','Assigned'],nextActions46()))}${card('System Snapshot','',tbl(['Metric','Value'],systemRows46()))}`}
function cleanSettings46(){return card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=bad onclick=startFreshWorkspace()>Start Fresh / Clear Sample Data</button><button class=ghost onclick=go('Fresh Start')>Fresh Start</button><button class=ghost onclick=go('Data Exchange')>Data Exchange</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=ghost onclick=runCleanup46()>Run Cleanup</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF462_VER}</b></p><p>Schema ${WF462_SCHEMA}</p>${tbl(['Metric','Value'],systemRows46())}<p class=muted>Use Start Fresh to remove sample/demo records and begin using Work Forge for real work.</p>`)}
function freshView46(){return card('Fresh Start Workspace',`<button class=bad onclick=startFreshWorkspace()>Start Fresh / Clear Sample Data</button><button class=ghost onclick=downloadFreshBackup()>Download Backup First</button><button class=soft onclick=seedRealStarter()>Create Minimal Real-Use Starter</button><button class=ghost onclick=go('Data Exchange')>Data Exchange</button>`,`<p class=need><b>This clears the current browser workspace records.</b></p><p class=muted>Use this when you are done testing with sample data and are ready to use Work Forge for real work. Preferences such as dark mode and collapsed navigation are preserved. A safety copy is stored locally before clearing.</p>${tbl(['Area','Current Records'],freshStats46())}<h3>What gets cleared</h3>${tbl(['Data Type','Cleared'],ARRAYS.map(k=>[k,'Yes']))}`)}
function cleanArchitecture46(){let layers=['qr.js','app.js','assets.js','kitting.js','reports.js','testing.js','reliability.js','production.js','inventory.js','closeout.js','people.js','dataio.js','polish.js','board-dnd.js','cleanup.js'];return card('Architecture',`<button class=ghost onclick=go('Test Harness')>Test Harness</button><button class=ghost onclick=runCleanup46()>Run Cleanup</button>`,`<p class=muted>v4.6.2 folds Fresh Start directly into cleanup so it appears without relying on another script chain.</p>${tbl(['Layer','Purpose'],layers.map(l=>[l,l=='cleanup.js'?'normalization, streamlined UI, built-in fresh start':'feature layer']))}`)}
window.splitList=split46;window.ensurePeople=ensurePeople46;window.startFreshWorkspace=startFreshWorkspace46;window.downloadFreshBackup=downloadFreshBackup46;window.seedRealStarter=seedRealStarter46;window.runCleanup46=function(){cleanDb46();save();draw();alert('Cleanup complete. Data normalized and stale queue entries removed.')};
cleanDb46();
views['Fresh Start']=freshView46;
P=uniq(ORDER.filter(p=>views[p]).concat(P.filter(p=>views[p]&&!ORDER.includes(p)&&p!='Diagnostics')));
views.Dashboard=cleanDashboard46;
views.Settings=cleanSettings46;
views.Architecture=cleanArchitecture46;
let oldTest46=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest46?oldTest46():'';let rows=cleanupChecks46();return html+card('v4.6.2 Cleanup & Fresh Start Checks',`<button class=ghost onclick=runCleanup46()>Run Cleanup</button><button class=bad onclick=startFreshWorkspace()>Start Fresh</button>`,tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
if(window.WF){WF.version=WF462_VER;WF.cleanup={clean:cleanDb46,checks:cleanupChecks46,split:split46,ensurePeople:ensurePeople46};WF.freshStart={emptyWorkspace:emptyWorkspace46,startFreshWorkspace:startFreshWorkspace46,downloadFreshBackup:downloadFreshBackup46,seedRealStarter:seedRealStarter46}}
let oldDraw46=draw;draw=function(){cleanDb46();oldDraw46();$('ver').textContent=WF462_VER;document.querySelectorAll('#view table').forEach(t=>{if(t.parentElement&&t.parentElement.classList.contains('wf45-table-wrap'))return;let w=document.createElement('div');w.className='wf45-table-wrap';t.parentNode.insertBefore(w,t);w.appendChild(t)})};
save=function(){db.version=WF462_VER;db.schema=WF462_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
save();draw();
})();
