const WF42_VER='v4.2 Evidence & Closeout Packages',WF42_SCHEMA=420;
(function(){
function ensureCloseout(j){j.closeoutPack=j.closeoutPack||{};let c=j.closeoutPack;c.asFound=c.asFound||'';c.asLeft=c.asLeft||'';c.summary=c.summary||'';c.labor=c.labor||'';c.evidence=Array.isArray(c.evidence)?c.evidence:[];c.measurements=Array.isArray(c.measurements)?c.measurements:[];c.finalReviewer=c.finalReviewer||'';c.reviewDate=c.reviewDate||'';c.ready=!!c.ready;return c}
function evidenceStatus(j){let c=ensureCloseout(j),need=[];if(!c.asFound)need.push('as-found condition');if(!c.asLeft)need.push('as-left condition');if(!c.summary)need.push('completion summary');if(!(j.steps||[]).every(s=>s.done))need.push('complete work steps');if((j.steps||[]).some(s=>s.result=='Fail'))need.push('resolve failed steps');if((db.actions||[]).some(a=>a.source==j.id&&a.status!='Closed'))need.push('close corrective actions');if((db.signoffs||[]).some(s=>s.source==j.id&&s.status!='Signed'))need.push('signoffs');return need}
function closeoutReady(j){return evidenceStatus(j).length==0}
function evidenceTable(j){let c=ensureCloseout(j);return c.evidence.length?tbl(['Type','Reference','Note'],c.evidence.map(e=>[e.type,e.ref,e.note])):'<p class=muted>No evidence references recorded.</p>'}
function measurementTable(j){let c=ensureCloseout(j);return c.measurements.length?tbl(['Measurement','Value','Units','Result'],c.measurements.map(m=>[m.name,m.value,m.units,m.result])):'<p class=muted>No measurements recorded.</p>'}
function partsUsedTable(j){let moves=(db.inventoryMoves||[]).filter(m=>m.job==j.id);return moves.length?tbl(['Type','Part','Qty','Date','By'],moves.map(m=>[m.type,m.part,m.qty,m.date,m.by])):'<p class=muted>No inventory movement recorded for this traveler.</p>'}
function closeoutForm(j){let c=ensureCloseout(j),missing=evidenceStatus(j);return`<div class=card><h3>${E(j.id)} · ${E(j.title)}</h3><p><span class=pill>${closeoutReady(j)?'Closeout Ready':'Closeout Needs Work'}</span> ${missing.length?'<span class=need>'+E(missing.join(', '))+'</span>':''}</p><label>As-found condition<textarea oninput='db.jobs[sel].closeoutPack.asFound=this.value;save()'>${E(c.asFound)}</textarea></label><label>As-left condition<textarea oninput='db.jobs[sel].closeoutPack.asLeft=this.value;save()'>${E(c.asLeft)}</textarea></label><label>Completion summary<textarea oninput='db.jobs[sel].closeoutPack.summary=this.value;db.jobs[sel].closeout=this.value;save()'>${E(c.summary)}</textarea></label><label>Labor notes<textarea oninput='db.jobs[sel].closeoutPack.labor=this.value;save()'>${E(c.labor)}</textarea></label><label>Final reviewer<input value='${E(c.finalReviewer)}' oninput='db.jobs[sel].closeoutPack.finalReviewer=this.value;save()'></label><div class=tools><button class=soft onclick=addEvidence()>Add Evidence Reference</button><button class=ghost onclick=addMeasurement()>Add Measurement</button><button class=ghost onclick=markCloseoutReady()>Mark Closeout Ready</button><button class=ghost onclick=printCloseoutPackage()>Print Closeout Package</button></div><h3>Evidence References</h3>${evidenceTable(j)}<h3>Measurements</h3>${measurementTable(j)}<h3>Parts Used</h3>${partsUsedTable(j)}</div>`}
function packageHTML(j){let c=ensureCloseout(j);return`<div class=card><h1>Closeout Package · ${E(j.id)}</h1><p><b>${E(j.title)}</b></p><p>Asset: ${E(j.asset||'')} · State: ${E(j.status)} · Ready: ${closeoutReady(j)?'YES':'NO'}</p><h2>Readiness</h2>${tbl(['Requirement','Status'],[['As-found',c.asFound?'Recorded':'Missing'],['As-left',c.asLeft?'Recorded':'Missing'],['Summary',c.summary?'Recorded':'Missing'],['Steps',(j.steps||[]).every(s=>s.done)?'Complete':'Open'],['Failures',(j.steps||[]).some(s=>s.result=='Fail')?'Unresolved':'Clear']])}<h2>As-found Condition</h2><p>${E(c.asFound)}</p><h2>As-left Condition</h2><p>${E(c.asLeft)}</p><h2>Completion Summary</h2><p>${E(c.summary||j.closeout||'')}</p><h2>Labor Notes</h2><p>${E(c.labor)}</p><h2>Measurements</h2>${measurementTable(j)}<h2>Evidence References</h2>${evidenceTable(j)}<h2>Parts Used</h2>${partsUsedTable(j)}<h2>Final Review</h2><p>Reviewer: ${E(c.finalReviewer)} · Date: ${E(c.reviewDate||'')}</p><div class=line></div></div>`}
if(!P.includes('Closeout'))P.splice(P.indexOf('Reports'),0,'Closeout');
views.Closeout=()=>{let j=db.jobs[sel]||db.jobs[0];return card('Evidence & Closeout',`<button class=soft onclick=markCloseoutReady()>Mark Ready</button><button class=ghost onclick=printCloseoutPackage()>Print Package</button><button class=ghost onclick=csvCloseout()>Closeout CSV</button>`,j?closeoutForm(j):'<p class=muted>No active traveler selected.</p>')};
let oldJob42=jobView;jobView=function(j){ensureCloseout(j);let html=oldJob42(j);return html.replace('</p>',` <span class=pill>${closeoutReady(j)?'Closeout Ready':'Closeout Open'}</span></p><div class=tools><button class=ghost onclick=go('Closeout')>Closeout</button><button class=ghost onclick=printCloseoutPackage()>Print Closeout</button></div>`)};
let oldPacket42=packetHTML;packetHTML=function(j){return oldPacket42(j)+`<h2>Closeout Package</h2>${packageHTML(j)}`};
let oldSet42=window.setState;window.setState=function(i,state){let j=db.jobs[i];if(state=='Complete'&&j&&!closeoutReady(j)){let miss=evidenceStatus(j);if(!confirm('Closeout is not ready: '+miss.join(', ')+'. Complete anyway?'))return}return oldSet42?oldSet42(i,state):(j.status=state,save(),draw())};
window.addEvidence=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;let c=ensureCloseout(j),type=prompt('Evidence type','Photo reference')||'Evidence',ref=prompt('File name, URL, or reference','')||'',note=prompt('Note','')||'';if(!ref)return;c.evidence.push({type,ref,note});log('Evidence added',j.id);save();draw()};
window.addMeasurement=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;let c=ensureCloseout(j),name=prompt('Measurement name','Run current')||'',value=prompt('Value','')||'',units=prompt('Units','')||'',result=prompt('Result','Pass')||'Pass';if(!name)return;c.measurements.push({name,value,units,result});log('Measurement added',j.id);save();draw()};
window.markCloseoutReady=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;let miss=evidenceStatus(j);if(miss.length&&!confirm('Missing: '+miss.join(', ')+'. Mark ready anyway?'))return;let c=ensureCloseout(j);c.ready=true;c.reviewDate=D();j.closeout=j.closeout||c.summary;log('Closeout marked ready',j.id);save();draw()};
window.printCloseoutPackage=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;let w=open('','_blank');if(!w)return alert('Allow pop-ups to print closeout packages.');w.document.write(`<link rel="stylesheet" href="style.css?v=4.2">${packageHTML(j)}`);w.document.close();w.print&&w.print();log('Closeout package printed',j.id);save()};
window.csvCloseout=function(){csv('workforge-closeout.csv',[['ID','Title','Asset','Ready','Missing','Evidence','Measurements','Reviewer','Review Date'],...db.jobs.concat(db.archive||[]).map(j=>{let c=ensureCloseout(j);return[j.id,j.title,j.asset,closeoutReady(j)?'YES':'NO',evidenceStatus(j).join('; '),c.evidence.length,c.measurements.length,c.finalReviewer,c.reviewDate]})])};
let oldReports42=views.Reports;views.Reports=()=>oldReports42()+card('Closeout Readiness Report',`<button class=ghost onclick=csvCloseout()>Closeout CSV</button>`,tbl(['Ready','ID','Title','Missing','Evidence','Measurements'],db.jobs.map(j=>{let c=ensureCloseout(j);return[closeoutReady(j)?'YES':'NO',j.id,j.title,evidenceStatus(j).join(', '),c.evidence.length,c.measurements.length]})));
let oldTest42=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest42?oldTest42():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.2 visible',WF42_VER.includes('v4.2'),WF42_VER);pass('Closeout page registered',P.includes('Closeout'),'nav');pass('Closeout records normalize',db.jobs.every(j=>!!ensureCloseout(j)),db.jobs.length+' jobs');pass('Readiness function works',!db.jobs[0]||Array.isArray(evidenceStatus(db.jobs[0])),'selected');pass('Print package available',typeof printCloseoutPackage=='function','print');pass('Closeout CSV available',typeof csvCloseout=='function','csv');return html+card('v4.2 Evidence & Closeout Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=ghost onclick=go('Architecture')>Architecture</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF42_VER}</b></p><p>Schema ${WF42_SCHEMA}</p><p class=muted>v4.2 adds structured closeout packages, evidence references, measurements, labor notes, and closeout readiness gates.</p>`);
if(window.WF){WF.version=WF42_VER;WF.closeout={ensureCloseout,evidenceStatus,closeoutReady,packageHTML}}
save=function(){db.version=WF42_VER;db.schema=WF42_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF42_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db.jobs.forEach(ensureCloseout);(db.archive||[]).forEach(ensureCloseout);db.schema=WF42_SCHEMA;save();draw();
})();
