const WF44_VER='v4.4 Import Export Merge Tools',WF44_SCHEMA=440;
(function(){
let PREVIEW=null;
const KEYS=['jobs','procedures','assets','items','labels','queue','actions','signoffs','archive','log','maintenance','inventoryMoves','people'];
function clone44(x){return JSON.parse(JSON.stringify(x))}
function arrays44(o){return KEYS.filter(k=>Array.isArray(o[k]))}
function countRows(o){return KEYS.map(k=>[k,Array.isArray(o[k])?o[k].length:0,Array.isArray(db[k])?db[k].length:0])}
function validateBackup(o){let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('JSON object',!!o&&typeof o=='object'&&!Array.isArray(o),'root');pass('Has schema or version',!!(o.schema||o.version),(o.version||'')+' '+(o.schema||''));pass('Known arrays found',arrays44(o).length>0,arrays44(o).join(', '));arrays44(o).forEach(k=>pass(k+' is array',Array.isArray(o[k]),String((o[k]||[]).length)));let ids={};arrays44(o).forEach(k=>(o[k]||[]).forEach(r=>{if(r&&r.id){if(ids[r.id])pass('Duplicate id '+r.id,false,k+' and '+ids[r.id]);else ids[r.id]=k}}));return rows}
function mergeArrays(current,incoming,key){let by=new Map((current||[]).map(x=>[x&&x[key]||JSON.stringify(x),x]));(incoming||[]).forEach(x=>{let id=x&&x[key]||JSON.stringify(x);by.set(id,Object.assign({},by.get(id)||{},x))});return [...by.values()]}
function mergedData(incoming){let out=clone44(db);KEYS.forEach(k=>{if(Array.isArray(incoming[k]))out[k]=k=='queue'?[...new Set([...(out[k]||[]),...(incoming[k]||[])])]:mergeArrays(out[k]||[],incoming[k],k=='log'?'t':'id')});out.version=WF44_VER;out.schema=WF44_SCHEMA;return out}
function previewHTML(){if(!PREVIEW)return'<p class=muted>No backup preview loaded. Use Preview Backup JSON first.</p>';let val=validateBackup(PREVIEW),ok=val.filter(r=>r[0]=='PASS').length,fail=val.length-ok;return`<div class=grid>${m('Incoming Arrays',arrays44(PREVIEW).length)}${m('Validation Pass',ok)}${m('Validation Fail',fail)}${m('Incoming Version',PREVIEW.version||'Unknown')}</div><h3>Record Counts</h3>${tbl(['Array','Incoming','Current'],countRows(PREVIEW))}<h3>Validation</h3>${tbl(['Result','Check','Detail'],val)}`}
function pick(fields){let o={version:WF44_VER,schema:WF44_SCHEMA,exportedAt:new Date().toISOString()};fields.forEach(k=>o[k]=clone44(db[k]||[]));return o}
function downloadJSON(name,o){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));a.download=name;a.click()}
function loadPreviewFile(file){let r=new FileReader();r.onload=()=>{try{PREVIEW=JSON.parse(r.result);go('Data Exchange')}catch(e){alert('Could not parse JSON: '+e.message)}};r.readAsText(file)}
if(!P.includes('Data Exchange'))P.splice(P.indexOf('Settings'),0,'Data Exchange');
views['Data Exchange']=()=>card('Data Exchange',`<input id=mergeFile type=file accept='.json' class=hide onchange='previewMergeFile(event)'><button class=soft onclick=mergeFile.click()>Preview Backup JSON</button><button class=ghost onclick=applyMerge()>Merge Preview</button><button class=ghost onclick=applyReplace()>Replace With Preview</button><button class=ghost onclick=exportFullBackup()>Full Backup</button><button class=ghost onclick=exportProceduresOnly()>Procedures Only</button><button class=ghost onclick=exportArchiveOnly()>Archive Only</button><button class=bad onclick=restoreLastBackup()>Restore Safety Copy</button>`,previewHTML()+card('Import Modes','',tbl(['Mode','Behavior'],[['Preview','Reads JSON and validates before touching data'],['Merge','Combines incoming records by ID and preserves current records'],['Replace','Replaces current project after making a safety copy'],['Safety Copy','Stored before merge or replace under workforge.lastSafetyCopy']])));
window.previewMergeFile=function(ev){let f=ev.target.files&&ev.target.files[0];if(f)loadPreviewFile(f)};
window.exportFullBackup=function(){downloadJSON('workforge-full-backup.json',pick(KEYS))};
window.exportProceduresOnly=function(){downloadJSON('workforge-procedures.json',pick(['procedures']))};
window.exportArchiveOnly=function(){downloadJSON('workforge-archive.json',pick(['archive','log']))};
window.applyMerge=function(){if(!PREVIEW)return alert('Preview a backup first.');let fails=validateBackup(PREVIEW).filter(r=>r[0]=='FAIL');if(fails.length&&!confirm('Validation has failures. Merge anyway?'))return;localStorage.setItem('workforge.lastSafetyCopy',JSON.stringify(db));db=mergedData(PREVIEW);save();log('Merged backup import','Data Exchange');go('Data Exchange')};
window.applyReplace=function(){if(!PREVIEW)return alert('Preview a backup first.');if(!confirm('Replace current Work Forge data with previewed backup? A safety copy will be stored.'))return;localStorage.setItem('workforge.lastSafetyCopy',JSON.stringify(db));db=Object.assign({version:WF44_VER,schema:WF44_SCHEMA},PREVIEW);KEYS.forEach(k=>db[k]=Array.isArray(db[k])?db[k]:[]);save();log('Replaced project from backup','Data Exchange');go('Data Exchange')};
window.restoreLastBackup=function(){let raw=localStorage.getItem('workforge.lastSafetyCopy');if(!raw)return alert('No safety copy found.');if(!confirm('Restore the last safety copy?'))return;db=JSON.parse(raw);save();go('Data Exchange')};
let oldSettings44=views.Settings;views.Settings=()=>oldSettings44()+card('Data Exchange Shortcuts',`<button class=ghost onclick=go('Data Exchange')>Open Data Exchange</button><button class=ghost onclick=exportFullBackup()>Full Backup</button>`,`<p class=muted>Use Data Exchange for previewed imports, merge/replace workflows, selective exports, and safety-copy restore.</p>`);
let oldTest44=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest44?oldTest44():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.4 visible',WF44_VER.includes('v4.4'),WF44_VER);pass('Data Exchange page registered',P.includes('Data Exchange'),'nav');pass('Validation works',Array.isArray(validateBackup(db)),'current db');pass('Merge function works',!!mergedData({jobs:[]}).jobs,'merge');pass('Selective backup works',!!pick(['jobs']).jobs,'backup');pass('Safety restore function exists',typeof restoreLastBackup=='function','restore');return html+card('v4.4 Import Export Merge Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
if(window.WF){WF.version=WF44_VER;WF.dataio={validateBackup,mergedData,pick}}
save=function(){db.version=WF44_VER;db.schema=WF44_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF44_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
KEYS.forEach(k=>db[k]=Array.isArray(db[k])?db[k]:[]);db.schema=WF44_SCHEMA;save();draw();
})();
