const WF461_VER='v4.6.1 Fresh Start Workspace',WF461_SCHEMA=461;
(function(){
const EMPTY_KEYS=['jobs','procedures','assets','items','labels','queue','actions','signoffs','archive','log','maintenance','inventoryMoves','people'];
function emptyWorkspace(){let o={version:WF461_VER,schema:WF461_SCHEMA,createdAt:new Date().toISOString(),workspaceName:'Real Work Forge Workspace'};EMPTY_KEYS.forEach(k=>o[k]=[]);return o}
function downloadFreshBackup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='workforge-before-fresh-start.json';a.click()}
function startFreshWorkspace(){if(!confirm('Start fresh and remove all current sample/demo records from this browser?'))return;if(confirm('Download a backup first?'))downloadFreshBackup();let prefs={dark:localStorage.getItem('workforge.dark'),nav:localStorage.getItem('workforge.navCollapsed')};localStorage.setItem('workforge.lastSafetyCopy',JSON.stringify(db));db=emptyWorkspace();if(prefs.dark!=null)localStorage.setItem('workforge.dark',prefs.dark);if(prefs.nav!=null)localStorage.setItem('workforge.navCollapsed',prefs.nav);save();page='Control Board';sel=0;draw();alert('Fresh workspace ready. Sample data has been cleared from this browser.');}
function seedRealStarter(){if(!confirm('Add a minimal real-use starter set with no sample jobs?'))return;db=emptyWorkspace();db.procedures.push({id:'PROC-001',title:'New Controlled Procedure',rev:1,status:'Draft',steps:[]});db.people.push({id:'PER-001',name:'Unassigned',role:'Placeholder',active:true,notes:'Replace with real people.'});db.labels=[];db.log.unshift({t:new Date().toLocaleString(),a:'Starter workspace created',d:'Fresh Start'});save();page='Procedures';draw();}
function freshStats(){return [['Jobs',db.jobs.length],['Procedures',db.procedures.length],['Assets',db.assets.length],['Parts / Tools',db.items.length],['People',db.people.length],['Labels',db.labels.length],['Archive',db.archive.length],['Inventory Moves',db.inventoryMoves.length]]}
if(!P.includes('Fresh Start'))P.splice(P.indexOf('Settings'),0,'Fresh Start');
views['Fresh Start']=()=>card('Fresh Start Workspace',`<button class=bad onclick=startFreshWorkspace()>Start Fresh / Clear Sample Data</button><button class=ghost onclick=downloadFreshBackup()>Download Backup First</button><button class=soft onclick=seedRealStarter()>Create Minimal Real-Use Starter</button><button class=ghost onclick=go('Data Exchange')>Data Exchange</button>`,`<p class=need><b>This clears the current browser workspace records.</b></p><p class=muted>Use this when you are done testing with sample data and are ready to use Work Forge for real work. Preferences such as dark mode and collapsed navigation are preserved. A safety copy is stored locally before clearing.</p>${tbl(['Area','Current Records'],freshStats())}<h3>What gets cleared</h3>${tbl(['Data Type','Cleared'],EMPTY_KEYS.map(k=>[k,'Yes']))}`);
let oldSettings461=views.Settings;views.Settings=()=>oldSettings461()+card('Fresh Start',`<button class=bad onclick=startFreshWorkspace()>Start Fresh / Clear Sample Data</button><button class=ghost onclick=go('Fresh Start')>Open Fresh Start</button>`,`<p class=muted>Clear sample/demo records and begin a real workspace while preserving app preferences.</p>`);
let oldDash461=views.Dashboard;views.Dashboard=()=>card('Workspace Status',`<button class=ghost onclick=go('Fresh Start')>Fresh Start</button><button class=ghost onclick=go('Data Exchange')>Backup / Import</button>`,tbl(['Area','Records'],freshStats()))+oldDash461();
let oldTest461=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest461?oldTest461():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.6.1 visible',WF461_VER.includes('v4.6.1'),WF461_VER);pass('Fresh Start page registered',P.includes('Fresh Start'),'nav');pass('Fresh start function available',typeof startFreshWorkspace=='function','start');pass('Backup function available',typeof downloadFreshBackup=='function','backup');pass('Empty workspace shape valid',EMPTY_KEYS.every(k=>Array.isArray(emptyWorkspace()[k])),EMPTY_KEYS.length+' arrays');return html+card('v4.6.1 Fresh Start Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
window.startFreshWorkspace=startFreshWorkspace;window.downloadFreshBackup=downloadFreshBackup;window.seedRealStarter=seedRealStarter;
if(window.WF){WF.version=WF461_VER;WF.freshStart={emptyWorkspace,startFreshWorkspace,downloadFreshBackup,seedRealStarter}}
let oldDraw461=draw;draw=function(){oldDraw461();$('ver').textContent=WF461_VER};
save=function(){db.version=WF461_VER;db.schema=WF461_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
db.version=WF461_VER;db.schema=WF461_SCHEMA;save();draw();
})();
