const WF41_VER='v4.1 Inventory Consumption',WF41_SCHEMA=410;
(function(){
function list41(v){return Array.isArray(v)?v.filter(Boolean):String(v||'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)}
function partItem(name){let q=String(name||'').toLowerCase();return db.items.find(i=>i.kind=='Part'&&String(i.name||'').toLowerCase()==q)||db.items.find(i=>i.kind=='Part'&&String(i.id||'').toLowerCase()==q)}
function reqParts41(j){return typeof reqParts=='function'?reqParts(j):[...new Set([...(j.parts||[]),...(j.steps||[]).flatMap(s=>list41(s.parts))])].filter(Boolean)}
function moveRows(){db.inventoryMoves=db.inventoryMoves||[];return db.inventoryMoves}
function issuedFor(jobId){return moveRows().filter(m=>m.job==jobId&&m.type=='Issue')}
function usageByPart(name){return moveRows().filter(m=>m.part==name)}
function usageByAsset(asset){return moveRows().filter(m=>m.asset==asset)}
function lowStock41(){return db.items.filter(i=>i.kind=='Part'&&Number(i.qty||0)<=Number(i.min||0))}
function issuePlan(j){return reqParts41(j).map(p=>{let item=partItem(p),already=issuedFor(j.id).filter(m=>m.part==p).reduce((n,m)=>n+Number(m.qty||0),0);return{part:p,item,need:1,issued:already,available:item?Number(item.qty||0):0,min:item?Number(item.min||0):0,loc:item?item.loc||'':'',status:!item?'No Record':already>=1?'Issued':Number(item.qty||0)>0?'Ready':'Short'}})}
function consumeJob(j,force=false){let rows=issuePlan(j),short=rows.filter(r=>['No Record','Short'].includes(r.status));if(short.length&&!force&&!confirm('Some parts are short or missing records. Issue available parts anyway?'))return;rows.forEach(r=>{if(r.issued>=r.need)return;if(!r.item)return;if(Number(r.item.qty||0)<=0)return;let q=Math.min(r.need-r.issued,Number(r.item.qty||0));r.item.qty=Number(r.item.qty||0)-q;moveRows().unshift({id:'MV-'+String(moveRows().length+1).padStart(4,'0'),type:'Issue',job:j.id,asset:j.asset||'',part:r.part,qty:q,date:D(),by:j.assigned||'',note:'Issued to traveler'});if(Number(r.item.qty||0)<Number(r.item.min||0))log('Part below minimum',r.part)});j.partsIssued=true;j.partsIssuedAt=D();log('Inventory issued',j.id);save();draw()}
function reverseJob(j){let moves=issuedFor(j.id);if(!moves.length)return alert('No issued parts found for this traveler.');if(!confirm('Return issued parts for '+j.id+' to inventory?'))return;moves.forEach(m=>{let item=partItem(m.part);if(item)item.qty=Number(item.qty||0)+Number(m.qty||0);m.reversed=true;m.type='Returned'});j.partsIssued=false;j.partsIssuedAt='';log('Inventory returned',j.id);save();draw()}
function inventoryTable(){return tbl(['Status','Part','Qty','Min','Location','Usage Count'],db.items.filter(i=>i.kind=='Part').map(i=>[Number(i.qty||0)<=Number(i.min||0)?'LOW':'OK',i.name,i.qty,i.min||0,i.loc||'',usageByPart(i.name).length]))}
function issueTable(j){return tbl(['Status','Part','Need','Issued','Available','Min','Location'],issuePlan(j).map(r=>[r.status,r.part,r.need,r.issued,r.available,r.min,r.loc]))}
function movesTable(){return tbl(['Type','ID','Date','Job','Asset','Part','Qty','By','Note'],moveRows().map(m=>[m.type,m.id,m.date,m.job,m.asset,m.part,m.qty,m.by,m.note||'']))}
function assetUsageTable(){return tbl(['Asset','Part Issues','Qty Issued','Jobs'],db.assets.map(a=>{let ms=usageByAsset(a.tag);return[a.tag,ms.length,ms.reduce((n,m)=>n+Number(m.qty||0),0),[...new Set(ms.map(m=>m.job))].join(', ')]}))}
if(!P.includes('Inventory Control'))P.splice(P.indexOf('Parts & Tools')+1,0,'Inventory Control');
views['Inventory Control']=()=>{let j=db.jobs[sel]||db.jobs[0];return card('Inventory Control',`<button class=soft onclick=issueSelectedJob()>Issue Parts to Selected Traveler</button><button class=ghost onclick=returnSelectedJobParts()>Return Selected Traveler Parts</button><button class=ghost onclick=csvInventoryMoves()>Moves CSV</button><button class=ghost onclick=csvInventoryStatus()>Inventory CSV</button>`,`<div class=grid>${m('Parts',db.items.filter(i=>i.kind=='Part').length)}${m('Low Stock',lowStock41().length)}${m('Moves',moveRows().length)}${m('Selected',j?j.id:'None')}</div><h3>Selected Traveler Issue Plan</h3>${j?issueTable(j):'<p class=muted>No traveler selected.</p>'}<h3>Part Inventory</h3>${inventoryTable()}<h3>Movement Ledger</h3>${movesTable()}<h3>Asset Usage Summary</h3>${assetUsageTable()}`)};
let oldJob41=jobView;jobView=function(j){let html=oldJob41(j);return html.replace('</p>',` <span class=pill>Parts ${j.partsIssued?'Issued':'Not Issued'}</span></p><div class=tools><button class=ghost onclick=issueSelectedJob()>Issue Parts</button><button class=ghost onclick=returnSelectedJobParts()>Return Parts</button><button class=ghost onclick=go('Inventory Control')>Inventory</button></div>${issueTable(j)}`)};
let oldPacket41=packetHTML;packetHTML=function(j){return oldPacket41(j).replace('<h3>Work Steps</h3>',`<h3>Inventory Issue Plan</h3>${issueTable(j)}<h3>Work Steps</h3>`)};
let oldReports41=views.Reports;views.Reports=()=>oldReports41()+card('Inventory Consumption Reports',`<button class=ghost onclick=csvInventoryMoves()>Moves CSV</button><button class=ghost onclick=csvInventoryStatus()>Inventory CSV</button><button class=ghost onclick=csvAssetUsage()>Asset Usage CSV</button>`,inventoryTable()+movesTable()+assetUsageTable());
let oldSetState41=window.setState;window.setState=function(i,state){let j=db.jobs[i];if(state=='Complete'&&j&&!j.partsIssued&&reqParts41(j).length){if(confirm('Issue required parts before completing this traveler?'))consumeJob(j,true)}return oldSetState41?oldSetState41(i,state):(j.status=state,save(),draw())};
window.issueSelectedJob=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;consumeJob(j,false)};
window.returnSelectedJobParts=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;reverseJob(j)};
window.csvInventoryMoves=function(){csv('workforge-inventory-moves.csv',[['Type','ID','Date','Job','Asset','Part','Qty','By','Note'],...moveRows().map(m=>[m.type,m.id,m.date,m.job,m.asset,m.part,m.qty,m.by,m.note||''])])};
window.csvInventoryStatus=function(){csv('workforge-inventory-status.csv',[['Status','Part','Qty','Min','Location','Usage Count'],...db.items.filter(i=>i.kind=='Part').map(i=>[Number(i.qty||0)<=Number(i.min||0)?'LOW':'OK',i.name,i.qty,i.min||0,i.loc||'',usageByPart(i.name).length])])};
window.csvAssetUsage=function(){csv('workforge-asset-part-usage.csv',[['Asset','Part Issues','Qty Issued','Jobs'],...db.assets.map(a=>{let ms=usageByAsset(a.tag);return[a.tag,ms.length,ms.reduce((n,m)=>n+Number(m.qty||0),0),[...new Set(ms.map(m=>m.job))].join('; ')]})])};
let oldTest41=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest41?oldTest41():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.1 visible',WF41_VER.includes('v4.1'),WF41_VER);pass('Inventory Control registered',P.includes('Inventory Control'),'nav');pass('Inventory moves array exists',Array.isArray(db.inventoryMoves),'moves '+moveRows().length);pass('Issue plan computes',!db.jobs[0]||Array.isArray(issuePlan(db.jobs[0])),'selected');pass('Low stock computes',Array.isArray(lowStock41()),lowStock41().length+' low');pass('CSV exports available',typeof csvInventoryMoves=='function'&&typeof csvInventoryStatus=='function','exports');return html+card('v4.1 Inventory Consumption Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=ghost onclick=go('Architecture')>Architecture</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF41_VER}</b></p><p>Schema ${WF41_SCHEMA}</p><p class=muted>v4.1 adds inventory issue, return, movement ledger, low-stock warnings, and usage reports.</p>`);
if(window.WF){WF.version=WF41_VER;WF.inventory={issuePlan,consumeJob,reverseJob,usageByPart,usageByAsset,lowStock:lowStock41}}
save=function(){db.version=WF41_VER;db.schema=WF41_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF41_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db.inventoryMoves=db.inventoryMoves||[];db.schema=WF41_SCHEMA;save();draw();
})();
