const WF34_VER='v3.4 Kitting & Readiness',WF34_SCHEMA=340;
(function(){
function list(v){return Array.isArray(v)?v.filter(Boolean):String(v||'').split(/[,;\n]/).map(s=>s.trim()).filter(Boolean)}
function findItem(name,kind){let q=String(name||'').toLowerCase();return db.items.find(i=>(!kind||i.kind==kind)&&String(i.name||'').toLowerCase()==q)||db.items.find(i=>(!kind||i.kind==kind)&&String(i.id||'').toLowerCase()==q)}
function partsFor(j){return [...new Set([...(j.parts||[]),...j.steps.flatMap(s=>list(s.parts))])].filter(Boolean)}
function toolsFor(j){return [...new Set([...(j.tools||[]),...j.steps.flatMap(s=>list(s.tools))])].filter(Boolean)}
function itemRow(kind,name){let item=findItem(name,kind),qty=item?Number(item.qty||0):0,loc=item?item.loc||'':'',cond=item?item.condition||'':'Missing record',ok=item&&(kind=='Part'?qty>0:qty>0&&/available/i.test(cond));return{kind,name,item,qty,loc,cond,status:ok?'Ready':'Missing'}}
function kitRows(j){return partsFor(j).map(n=>itemRow('Part',n)).concat(toolsFor(j).map(n=>itemRow('Tool',n)))}
function missingRows(j){return kitRows(j).filter(r=>r.status!='Ready')}
function kitState(j){let rows=kitRows(j);if(!rows.length)return'Not Checked';let miss=missingRows(j).length;if(!miss)return'Ready';if(miss<rows.length)return'Partial';return'Missing'}
function kitSummary(j){let rows=kitRows(j),miss=missingRows(j);return{required:rows.length,missing:miss.length,ready:rows.length-miss.length,state:kitState(j)}}
function ensureKit(j){j.kit=j.kit||{};j.kit.status=j.kit.status||kitState(j);j.kit.pulledBy=j.kit.pulledBy||'';j.kit.checkedAt=j.kit.checkedAt||'';j.kit.notes=j.kit.notes||'';j.kit.holdReason=j.kit.holdReason||'';return j.kit}
function init34(){db.schema=WF34_SCHEMA;db.version=WF34_VER;db.jobs.forEach(ensureKit);(db.archive||[]).forEach(ensureKit)}
function statusClass(s){return s=='Ready'?'ok':s=='Not Checked'?'muted':'need'}
function kitBadge(j){let s=kitState(j);return`<span class='pill ${statusClass(s)}'>Kit ${E(s)}</span>`}
function pullSheetHTML(j){let rows=kitRows(j),sum=kitSummary(j);return`<div class=card><h2>Pull Sheet · ${E(j.id)} · ${E(j.title)}</h2><p>${kitBadge(j)} <span class=pill>${sum.ready}/${sum.required} ready</span></p><p><b>Assigned:</b> ${E(j.assigned||'')} · <b>Due:</b> ${E(j.due||'')}</p>${tbl(['Type','Required Item','On Hand','Condition','Location','Pull Status'],rows.map(r=>[r.kind,r.name,r.item?r.qty:'No record',r.cond,r.loc,r.status]))}<p><b>Kit notes:</b> ${E((j.kit&&j.kit.notes)||'')}</p><p>Picked by:</p><div class=line></div><p>Checked by:</p><div class=line></div></div>`}
function kittingTable(){return tbl(['Kit','ID','Title','Ready','Missing','Pulled By','Checked','Hold Reason'],db.jobs.map(j=>{ensureKit(j);let s=kitSummary(j);return[kitState(j),j.id,j.title,s.ready+'/'+s.required,s.missing,j.kit.pulledBy,j.kit.checkedAt,j.kit.holdReason]}))}
function shortageTable(){let rows=[];db.jobs.forEach(j=>missingRows(j).forEach(r=>rows.push([j.id,j.title,r.kind,r.name,r.item?r.qty:'No record',r.loc,r.cond])));return rows.length?tbl(['Job','Title','Type','Missing','On Hand','Location','Condition'],rows):'<p class=muted>No shortages detected.</p>'}
if(!P.includes('Pull Sheets'))P.splice(P.indexOf('Kitting')+1,0,'Pull Sheets');
views.Kitting=()=>card('Kitting & Readiness',`<button class=soft onclick=markSelectedKitReady()>Mark Selected Kit Ready</button><button class=ghost onclick=holdMissingKits()>Hold Missing Kits</button><button class=ghost onclick=printSelectedPullSheet()>Print Pull Sheet</button><button class=ghost onclick=csvKittingV34()>Kitting CSV</button>`,kittingTable()+card('Shortage Report','',shortageTable()));
views['Pull Sheets']=()=>{let j=db.jobs[sel]||db.jobs[0];return card('Pull Sheets',`<button class=soft onclick=printSelectedPullSheet()>Print Selected Pull Sheet</button><button class=ghost onclick=markSelectedKitReady()>Mark Kit Ready</button><button class=ghost onclick=holdSelectedForParts()>Hold For Parts</button>`,pullSheetHTML(j||{}))};
views.Dashboard=()=>`<div class=grid>${m('Ready Kits',db.jobs.filter(j=>kitState(j)=='Ready').length)}${m('Partial Kits',db.jobs.filter(j=>kitState(j)=='Partial').length)}${m('Missing Kits',db.jobs.filter(j=>kitState(j)=='Missing').length)}${m('Not Checked',db.jobs.filter(j=>kitState(j)=='Not Checked').length)}</div>${db.jobs.map((j,i)=>`<div class=row onclick='sel=${i};go("Jobs")'><div><b>${E(j.title)}</b><div class=muted>${j.id} · ${j.status} · ${closeout(j)} · Kit ${kitState(j)}</div></div><span class=pill>${pct(j)}%</span></div>`).join('')}`;
let oldJobView34=jobView;jobView=function(j){ensureKit(j);let panel=` ${kitBadge(j)} <span class=pill>${kitSummary(j).ready}/${kitSummary(j).required} ready</span></p><div class=tools><button class=ghost onclick=markSelectedKitReady()>Mark Kit Ready</button><button class=ghost onclick=holdSelectedForParts()>Hold For Parts</button><button class=ghost onclick=printSelectedPullSheet()>Print Pull Sheet</button></div>${tbl(['Type','Required','On Hand','Condition','Location','Status'],kitRows(j).map(r=>[r.kind,r.name,r.item?r.qty:'No record',r.cond,r.loc,r.status]))}<label>Kit pulled by<input value='${E(j.kit.pulledBy)}' oninput='j.kit.pulledBy=this.value;save()'></label><label>Kit notes<textarea oninput='j.kit.notes=this.value;save()'>${E(j.kit.notes)}</textarea></label>`;return oldJobView34(j).replace('</p>',panel)};
let oldPacketHTML34=packetHTML;packetHTML=function(j){return oldPacketHTML34(j).replace('<h3>Work Steps</h3>',`<h3>Kit Pull Sheet</h3>${pullSheetHTML(j)}<h3>Work Steps</h3>`)};
let oldReports34=views.Reports;views.Reports=()=>oldReports34()+card('Kitting Readiness Reports',`<button class=ghost onclick=csvKittingV34()>Kitting CSV</button><button class=ghost onclick=csvShortages()>Shortages CSV</button>`,kittingTable()+shortageTable());
views.Diagnostics=()=>{let rows=wf34Checks(),ok=rows.filter(r=>r[0]=='PASS').length,fail=rows.length-ok;return card('Split Build Diagnostics',`<button class=soft onclick='go("Diagnostics")'>Run Diagnostics</button><button class=ghost onclick=exportJSON()>Backup JSON</button>`,`<div class=grid>${m('Checks',rows.length)}${m('Pass',ok)}${m('Fail',fail)}${m('Version','3.4')}</div>${tbl(['Result','Check','Detail'],rows)}<p class=muted>These checks validate kitting readiness, pull sheets, shortages, QR rendering, and the split build.</p>`)};
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Diagnostics')>Open Diagnostics</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF34_VER}</b></p><p>Schema ${WF34_SCHEMA}</p><p class=muted>Use Diagnostics to validate kitting, pull sheets, QR labels, and the split build.</p>`);
window.markSelectedKitReady=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;ensureKit(j);let miss=missingRows(j);if(miss.length&&!confirm('Kit has missing items. Mark ready anyway?'))return;j.kit.status='Ready';j.kit.checkedAt=D();j.kit.holdReason='';log('Kit marked ready',j.id);save();draw()};
window.holdSelectedForParts=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;ensureKit(j);j.status='Hold';j.kit.status=kitState(j);j.kit.holdReason=missingRows(j).map(r=>r.name).join(', ')||'Held for kitting';log('Held for parts/tools',j.id);save();draw()};
window.holdMissingKits=function(){db.jobs.forEach(j=>{ensureKit(j);if(['Missing','Partial'].includes(kitState(j))){j.status='Hold';j.kit.holdReason=missingRows(j).map(r=>r.name).join(', ')}});log('Missing kits placed on hold','Kitting');save();draw()};
window.printSelectedPullSheet=function(){let j=db.jobs[sel]||db.jobs[0];if(!j)return;let w=open('','_blank');if(!w)return alert('Allow pop-ups to print pull sheets.');w.document.write(`<link rel="stylesheet" href="style.css?v=3.4">${pullSheetHTML(j)}`);w.document.close();w.print&&w.print();log('Pull sheet printed',j.id);save()};
window.csvKittingV34=function(){csv('workforge-kitting-readiness.csv',[['Kit','ID','Title','Ready','Required','Missing Count','Missing Items','Pulled By','Checked At','Hold Reason'],...db.jobs.map(j=>{let s=kitSummary(j);return[kitState(j),j.id,j.title,s.ready,s.required,s.missing,missingRows(j).map(r=>r.name).join('; '),(j.kit||{}).pulledBy,(j.kit||{}).checkedAt,(j.kit||{}).holdReason]})])};
window.csvShortages=function(){let rows=[];db.jobs.forEach(j=>missingRows(j).forEach(r=>rows.push([j.id,j.title,r.kind,r.name,r.item?r.qty:'No record',r.loc,r.cond])));csv('workforge-shortages.csv',[['Job','Title','Type','Missing','On Hand','Location','Condition'],...rows])};
function wf34Checks(){let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('Version visible',WF34_VER.includes('v3.4'),WF34_VER);pass('Schema migrated',db.schema===WF34_SCHEMA,'schema '+db.schema);pass('Kitting page registered',P.includes('Kitting'),'nav');pass('Pull Sheets page registered',P.includes('Pull Sheets'),'nav');pass('All jobs have kit records',db.jobs.every(j=>!!j.kit),db.jobs.length+' jobs');pass('Kit rows compute',db.jobs.every(j=>Array.isArray(kitRows(j))),db.jobs.length+' jobs');pass('Shortage report works',typeof shortageTable()=='string','shortage table');pass('Print pull sheet available',typeof printSelectedPullSheet=='function','print');pass('QR renderer available',typeof wfQrSvg=='function','qr.js');P.forEach(p=>{try{let html=views[p]();pass('Render '+p,typeof html=='string'&&html.length>0,html.length+' chars')}catch(e){pass('Render '+p,false,e.message)}});return rows}
save=function(){db.version=WF34_VER;db.schema=WF34_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF34_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
init34();save();draw();
})();
