const WF43_VER='v4.3 Assignment & Workload',WF43_SCHEMA=430;
(function(){
function peopleNames(){let s=new Set();(db.people||[]).forEach(p=>s.add(p.name));(db.jobs||[]).forEach(j=>{if(j.assigned)s.add(j.assigned)});(db.actions||[]).forEach(a=>{if(a.owner)s.add(a.owner)});(db.signoffs||[]).forEach(x=>{if(x.reviewer)s.add(x.reviewer)});return [...s].filter(Boolean).sort()}
function ensurePeople(){db.people=Array.isArray(db.people)?db.people:[];peopleNames().forEach(n=>{if(!db.people.some(p=>p.name==n))db.people.push({id:'PER-'+String(db.people.length+1).padStart(3,'0'),name:n,role:'Technician',active:true,notes:''})})}
function days43(d){return d?Math.ceil((new Date(d)-new Date(D()))/86400000):999}
function workFor(n){return{jobs:(db.jobs||[]).filter(j=>j.assigned==n),actions:(db.actions||[]).filter(a=>a.owner==n&&a.status!='Closed'),signoffs:(db.signoffs||[]).filter(s=>s.reviewer==n&&s.status!='Signed')}}
function loadScore(n){let w=workFor(n);return w.jobs.length*3+w.actions.length*2+w.signoffs.length}
function overdueFor(n){let w=workFor(n);return w.jobs.filter(j=>days43(j.due)<0).length+w.actions.filter(a=>days43(a.due)<0).length}
function personRows(){ensurePeople();return db.people.map(p=>{let w=workFor(p.name);return[p.active?'Active':'Inactive',p.name,p.role,w.jobs.length,w.actions.length,w.signoffs.length,overdueFor(p.name),loadScore(p.name)]})}
function personCards(){ensurePeople();return db.people.map((p,i)=>{let w=workFor(p.name);return`<div class=step><div class=top><div><b>${E(p.name)}</b><br><span class=muted>${E(p.role)} · ${p.active?'Active':'Inactive'} · load ${loadScore(p.name)}</span></div><div class=tools><button class=ghost onclick='editPerson(${i})'>Edit</button><button class=ghost onclick='assignSelectedTo("${E(p.name)}")'>Assign Selected</button></div></div>${tbl(['Type','ID','Title','Due/Date','Status'],[...w.jobs.map(j=>['Job',j.id,j.title,j.due,j.status]),...w.actions.map(a=>['Action',a.id,a.title,a.due,a.status]),...w.signoffs.map(s=>['Signoff',s.id,s.role,s.date,s.status])])}</div>`}).join('')}
function reviewerRows(){return tbl(['Reviewer','Pending Signoffs','Sources'],peopleNames().map(n=>{let s=(db.signoffs||[]).filter(x=>x.reviewer==n&&x.status!='Signed');return[n,s.length,s.map(x=>x.source).join(', ')]}))}
function workloadTable(){return tbl(['Status','Person','Role','Jobs','Actions','Signoffs','Overdue','Load Score'],personRows())}
if(!P.includes('People'))P.splice(P.indexOf('Schedule')+1,0,'People');
if(!P.includes('Workload'))P.splice(P.indexOf('People')+1,0,'Workload');
views.People=()=>{ensurePeople();return card('People',`<button class=soft onclick=newPerson()>New Person</button><button class=ghost onclick=csvPeople()>People CSV</button>`,personCards()||'<p class=muted>No people yet.</p>')};
views.Workload=()=>card('Assignment & Workload',`<button class=soft onclick=balanceWorkload()>Suggest Rebalance</button><button class=ghost onclick=csvWorkload()>Workload CSV</button><button class=ghost onclick=csvReviewerBacklog()>Reviewer CSV</button>`,`<div class=grid>${m('People',peopleNames().length)}${m('Overdue',personRows().reduce((n,r)=>n+Number(r[6]||0),0))}${m('Pending Signoffs',(db.signoffs||[]).filter(s=>s.status!='Signed').length)}${m('Open Actions',(db.actions||[]).filter(a=>a.status!='Closed').length)}</div><h3>Workload Summary</h3>${workloadTable()}<h3>Reviewer Backlog</h3>${reviewerRows()}`);
let oldJob43=jobView;jobView=function(j){let html=oldJob43(j);return html.replace('</p>',` <span class=pill>Assigned ${E(j.assigned||'Unassigned')}</span></p><label>Assigned Person<input value='${E(j.assigned||'')}' oninput='j.assigned=this.value;ensurePeople();save()'></label>`)};
let oldDash43=views.Dashboard;views.Dashboard=()=>`<div class=grid>${m('People',peopleNames().length)}${m('Unassigned',db.jobs.filter(j=>!j.assigned).length)}${m('Reviewer Backlog',(db.signoffs||[]).filter(s=>s.status!='Signed').length)}${m('Workload Alerts',personRows().filter(r=>Number(r[7])>=8||Number(r[6])>0).length)}</div>${oldDash43()}`;
let oldReports43=views.Reports;views.Reports=()=>oldReports43()+card('Assignment & Workload Reports',`<button class=ghost onclick=csvWorkload()>Workload CSV</button><button class=ghost onclick=csvPeople()>People CSV</button><button class=ghost onclick=csvReviewerBacklog()>Reviewer CSV</button>`,workloadTable()+reviewerRows());
window.newPerson=function(){ensurePeople();let name=prompt('Name','New Person');if(!name)return;db.people.unshift({id:'PER-'+String(db.people.length+1).padStart(3,'0'),name,role:prompt('Role','Technician')||'Technician',active:true,notes:''});save();draw()};
window.editPerson=function(i){let p=db.people[i];if(!p)return;p.name=prompt('Name',p.name)||p.name;p.role=prompt('Role',p.role)||p.role;p.active=confirm('Keep active?');save();draw()};
window.assignSelectedTo=function(name){let j=db.jobs[sel]||db.jobs[0];if(!j)return;j.assigned=name;ensurePeople();log('Assigned traveler',j.id+' -> '+name);save();draw()};
window.balanceWorkload=function(){ensurePeople();let ps=db.people.filter(p=>p.active);if(!ps.length)return alert('Add active people first.');let un=db.jobs.filter(j=>!j.assigned);if(!un.length)return alert('No unassigned jobs found.');un.forEach(j=>{let p=[...ps].sort((a,b)=>loadScore(a.name)-loadScore(b.name))[0];j.assigned=p.name});log('Workload rebalance suggested','assigned '+un.length+' jobs');save();draw()};
window.csvPeople=function(){ensurePeople();csv('workforge-people.csv',[['ID','Name','Role','Active','Notes'],...db.people.map(p=>[p.id,p.name,p.role,p.active?'YES':'NO',p.notes])])};
window.csvWorkload=function(){csv('workforge-workload.csv',[['Status','Person','Role','Jobs','Actions','Signoffs','Overdue','Load Score'],...personRows()])};
window.csvReviewerBacklog=function(){csv('workforge-reviewer-backlog.csv',[['Reviewer','Pending Signoffs','Sources'],...peopleNames().map(n=>{let s=(db.signoffs||[]).filter(x=>x.reviewer==n&&x.status!='Signed');return[n,s.length,s.map(x=>x.source).join('; ')]})])};
let oldTest43=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest43?oldTest43():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.3 visible',WF43_VER.includes('v4.3'),WF43_VER);pass('People page registered',P.includes('People'),'nav');pass('Workload page registered',P.includes('Workload'),'nav');pass('People array exists',Array.isArray(db.people),'people '+(db.people||[]).length);pass('Workload rows compute',Array.isArray(personRows()),personRows().length+' rows');pass('Assignment helpers available',typeof assignSelectedTo=='function'&&typeof balanceWorkload=='function','helpers');pass('CSV exports available',typeof csvPeople=='function'&&typeof csvWorkload=='function','exports');return html+card('v4.3 Assignment & Workload Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=ghost onclick=go('Architecture')>Architecture</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF43_VER}</b></p><p>Schema ${WF43_SCHEMA}</p><p class=muted>v4.3 adds people, assignment, workload, reviewer backlog, and reassignment helpers.</p>`);
if(window.WF){WF.version=WF43_VER;WF.people={ensurePeople,workFor,loadScore,overdueFor}}
save=function(){db.version=WF43_VER;db.schema=WF43_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF43_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
ensurePeople();db.schema=WF43_SCHEMA;save();draw();
})();
