const WF45_VER='v4.5 Mobile & Print Polish',WF45_SCHEMA=450;
(function(){
function inject45(){if(document.getElementById('wf45-style'))return;let s=document.createElement('style');s.id='wf45-style';s.textContent=`
:root{--wf45-gap:12px} body.nav-collapsed aside{width:74px;min-width:74px;overflow:hidden} body.nav-collapsed aside h2,body.nav-collapsed aside p,body.nav-collapsed #ver{display:none} body.nav-collapsed .nav button{font-size:0;padding:12px 8px} body.nav-collapsed .nav button::first-letter{font-size:14px}.wf-mobile-table{display:none}.wf45-toolbar{position:sticky;top:0;z-index:10;background:var(--paper,#fff);padding:8px;border-bottom:1px solid #ddd}.dark .wf45-toolbar{background:#111827;border-color:#374151}.wf45-print-only{display:none}.wf45-section-break{break-before:page;page-break-before:always}.wf45-screen-note{font-size:12px;opacity:.75}.wf45-table-wrap{overflow-x:auto;max-width:100%}@media(max-width:760px){.app{display:block}aside{position:relative;width:auto;min-height:0}.nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.top{position:sticky;top:0;z-index:9;display:block}.tools{gap:6px}.tools button,button,input,select,textarea{min-height:42px}table{display:block;overflow-x:auto;white-space:nowrap}.grid{grid-template-columns:1fr!important}.card,.step{margin:8px 0}.wf-mobile-table{display:block}.hide-mobile{display:none!important}}@media print{aside,.top,.nav,.tools,button,input[type=file],.wf45-no-print{display:none!important}body{background:white!important;color:black!important}.app,main{display:block!important;width:auto!important}.card,.step{box-shadow:none!important;border:1px solid #999!important;break-inside:avoid;page-break-inside:avoid}.wf45-print-only{display:block}table{font-size:10pt;width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:4px}h1,h2,h3{break-after:avoid}.label{break-inside:avoid}.line{border-bottom:1px solid #111;height:28px}}`;document.head.appendChild(s)}
function applyPrefs(){try{if(localStorage.getItem('workforge.dark')=='1')document.body.classList.add('dark');if(localStorage.getItem('workforge.navCollapsed')=='1')document.body.classList.add('nav-collapsed')}catch{}}
function toggleNav45(){document.body.classList.toggle('nav-collapsed');localStorage.setItem('workforge.navCollapsed',document.body.classList.contains('nav-collapsed')?'1':'0')}
function toggleDark45(){document.body.classList.toggle('dark');localStorage.setItem('workforge.dark',document.body.classList.contains('dark')?'1':'0')}
function printCurrent45(){window.print()}
function wrapTables45(){document.querySelectorAll('#view table').forEach(t=>{if(t.parentElement&&t.parentElement.classList.contains('wf45-table-wrap'))return;let w=document.createElement('div');w.className='wf45-table-wrap';t.parentNode.insertBefore(w,t);w.appendChild(t)})}
function addTopButtons45(){let box=document.querySelector('.top .tools');if(!box||document.getElementById('wf45NavBtn'))return;let nav=document.createElement('button');nav.id='wf45NavBtn';nav.className='ghost';nav.textContent='Nav';nav.onclick=toggleNav45;box.prepend(nav);let print=document.createElement('button');print.id='wf45PrintBtn';print.className='ghost';print.textContent='Print';print.onclick=printCurrent45;box.appendChild(print);let dark=[...box.querySelectorAll('button')].find(b=>b.textContent.trim()=='Dark Mode');if(dark)dark.onclick=toggleDark45}
function printPacketBuilder(){let j=db.jobs[sel]||db.jobs[0];if(!j)return alert('No traveler selected.');let w=open('','_blank');if(!w)return alert('Allow pop-ups to print packet.');let sections=[];sections.push(`<h1>Work Forge Print Packet</h1><p>${E(j.id)} · ${E(j.title)}</p>`);if(typeof packetHTML=='function')sections.push(packetHTML(j));if(typeof WF!='undefined'&&WF.closeout&&WF.closeout.packageHTML)sections.push(`<div class=wf45-section-break>${WF.closeout.packageHTML(j)}</div>`);w.document.write(`<link rel="stylesheet" href="style.css?v=4.5"><style>${document.getElementById('wf45-style').textContent}</style>${sections.join('')}`);w.document.close();w.print&&w.print()}
function mobileCards(){return card('Mobile & Print Polish',`<button class=soft onclick=toggleNav45()>Collapse / Expand Navigation</button><button class=ghost onclick=toggleDark45()>Toggle Persistent Dark Mode</button><button class=ghost onclick=printCurrent45()>Print Current Page</button><button class=ghost onclick=printPacketBuilder()>Print Selected Packet</button>`,`<div class=grid>${m('Viewport',innerWidth+' px')}${m('Nav',document.body.classList.contains('nav-collapsed')?'Collapsed':'Open')}${m('Dark',document.body.classList.contains('dark')?'On':'Off')}${m('Print CSS','Ready')}</div><p class=muted>v4.5 adds sticky mobile controls, persistent dark mode, collapsible navigation, horizontal table wrapping, and print-focused layout rules.</p>${tbl(['Feature','Status'],[['Collapsible navigation','Enabled'],['Persistent dark mode','Enabled'],['Mobile table wrapping','Enabled'],['Print page cleanup','Enabled'],['Selected packet print helper','Enabled']])}`)}
if(!P.includes('Mobile / Print'))P.splice(P.indexOf('Settings'),0,'Mobile / Print');
views['Mobile / Print']=()=>mobileCards();
let oldSettings45=views.Settings;views.Settings=()=>oldSettings45()+card('Mobile & Print Shortcuts',`<button class=ghost onclick=go('Mobile / Print')>Open Mobile / Print</button><button class=ghost onclick=toggleNav45()>Toggle Navigation</button><button class=ghost onclick=printPacketBuilder()>Print Selected Packet</button>`,`<p class=muted>v4.5 keeps the app usable on smaller screens and improves printed packets, reports, labels, and travelers.</p>`);
let oldReports45=views.Reports;views.Reports=()=>oldReports45()+card('Print Readiness',`<button class=ghost onclick=printCurrent45()>Print Reports</button>`,tbl(['Area','Polish'],[['Tables','Horizontal wrap on screen, bordered on print'],['Cards','Avoid page breaks inside cards'],['Controls','Hidden while printing'],['Packets','Selected packet print helper'],['Dark mode','Persistent preference']]))
let oldTest45=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest45?oldTest45():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.5 visible',WF45_VER.includes('v4.5'),WF45_VER);pass('Mobile / Print page registered',P.includes('Mobile / Print'),'nav');pass('Style injected',!!document.getElementById('wf45-style'),'css');pass('Nav toggle available',typeof toggleNav45=='function','nav');pass('Dark preference available',typeof toggleDark45=='function','dark');pass('Packet print helper available',typeof printPacketBuilder=='function','packet');return html+card('v4.5 Mobile & Print Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
window.toggleNav45=toggleNav45;window.toggleDark45=toggleDark45;window.printCurrent45=printCurrent45;window.printPacketBuilder=printPacketBuilder;
if(window.WF){WF.version=WF45_VER;WF.polish={toggleNav:toggleNav45,toggleDark:toggleDark45,printCurrent:printCurrent45,printPacket:printPacketBuilder}}
let oldDraw45=draw;draw=function(){oldDraw45();addTopButtons45();wrapTables45();$('ver').textContent=WF45_VER};
save=function(){db.version=WF45_VER;db.schema=WF45_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
inject45();applyPrefs();db.schema=WF45_SCHEMA;save();draw();
if(!window.WF_BOARD_DND_LOADER){window.WF_BOARD_DND_LOADER=true;let s=document.createElement('script');s.src='board-dnd.js?v=4.5.1';document.body.appendChild(s)}
})();
