const WF40_VER='v4.0 Production Control',WF40_SCHEMA=400;
(function(){
const STATES=['Draft','Ready for Kitting','Waiting on Parts','Kitted','Ready to Start','In Progress','Hold','Waiting on Signoff','Complete'];
function days(d){return d?Math.ceil((new Date(d)-new Date(D()))/86400000):999}
function step40(s){return typeof step=='function'?step(s):(typeof s=='string'?{t:s,type:'Work',parts:'',tools:'',evidence:'',hold:false,done:false,result:'Not Checked',initials:''}:{t:s.t||'Untitled step',type:s.type||'Work',parts:s.parts||'',tools:s.tools||'',evidence:s.evidence||'',hold:!!s.hold,done:!!s.done,result:s.result||'Not Checked',initials:s.initials||''})}
function snap40(p){return JSON.parse(JSON.stringify({id:p.id,title:p.title,rev:p.rev||1,status:p.status,steps:(p.steps||[]).map(step40)}))}
function allJobs40(){return (db.jobs||[]).concat(db.archive||[])}
function kit40(j){try{return typeof kitStatus=='function'?kitStatus(j):((j.kit&&j.kit.status)||'Not Checked')}catch{return(j.kit&&j.kit.status)||'Not Checked'}}
function reqSigs(j){return (db.signoffs||[]).filter(s=>s.source==j.id&&s.status!='Signed').length}
function reqActs(j){return (db.actions||[]).filter(a=>a.source==j.id&&a.status!='Closed').length}
function done40(j){return j.steps&&j.steps.length&&j.steps.every(s=>s.done)}
function gate(j,target){let k=kit40(j),errs=[];if(['Kitted','Ready to Start','In Progress'].includes(target)&&!['Ready','Kitted'].includes(k))errs.push('kit is not ready');if(target=='Complete'&&!done40(j))errs.push('steps incomplete');if(target=='Complete'&&reqActs(j))errs.push('open corrective actions');if(target=='Complete'&&reqSigs(j))errs.push('pending signoffs');if(target=='Waiting on Signoff'&&!done40(j))errs.push('steps incomplete');return errs}
function setState(i,state){let j=db.jobs[i];if(!j)return;let errs=gate(j,state);if(errs.length&&!confirm('Gate warning: '+errs.join(', ')+'. Move anyway?'))return;j.status=state;if(state=='Complete')j.closeout=j.closeout||'Completed by production control board.';log('Lifecycle state changed',j.id+' -> '+state);save();draw()}
function card40(j,i){return`<div class=step><b>${E(j.id)} · ${E(j.title)}</b><br><span class=muted>${E(j.asset||'No asset')} · Due ${E(j.due||'')} · Kit ${E(kit40(j))} · ${pct(j)}%</span><br><span class=muted>Actions ${reqActs(j)} · Signoffs ${reqSigs(j)}</span><div class=tools><button class=ghost onclick='sel=${i};go("Jobs")'>Open</button><button class=ghost onclick='quickNext(${i})'>Next</button><button class=ghost onclick='printProductionPacket(${i})'>Packet</button></div></div>`}
function board(){return`<div class=grid>${STATES.map(st=>`<div class=card><h3>${st}</h3>${db.jobs.filter(j=>(j.status||'Draft')==st).map(j=>card40(j,db.jobs.indexOf(j))).join('')||'<p class=muted>No travelers.</p>'}</div>`).join('')}</div>`}
function schedule(){let rows=[...db.jobs].sort((a,b)=>days(a.due)-days(b.due));return tbl(['Due','Age','State','ID','Title','Asset','Kit','Assigned'],rows.map(j=>[j.due||'',days(j.due)<0?Math.abs(days(j.due))+' overdue':days(j.due)+' days',j.status,j.id,j.title,j.asset||'',kit40(j),j.assigned||'']))}
function recur(){db.maintenance=db.maintenance||[];return card('Recurring Maintenance Templates',`<button class=soft onclick=newMaintenancePlan()>New PM Template</button><button class=ghost onclick=generateDueMaintenance()>Generate Due Travelers</button><button class=ghost onclick=csvMaintenance()>PM CSV</button>`,tbl(['Status','ID','Procedure','Asset','Interval','Next Due','Last Generated'],db.maintenance.map(p=>[p.status,p.id,p.proc,p.asset,p.interval,p.nextDue,p.lastGenerated||''])))}
function packetSections(j){return`<div class=card><h1>Production Packet · ${E(j.id)}</h1><p><b>${E(j.title)}</b></p><p>State: ${E(j.status)} · Asset: ${E(j.asset||'')} · Due: ${E(j.due||'')}</p><h2>Gate Review</h2>${tbl(['Gate','Result'],[['Kit',kit40(j)],['Steps',done40(j)?'Complete':'Open'],['Corrective Actions',reqActs(j)],['Signoffs',reqSigs(j)],['Closeout',closeout(j)]])}${packetHTML(j)}<h2>Closeout Sheet</h2><p>As-found condition:</p><div class=line></div><p>As-left condition:</p><div class=line></div><p>Completion notes:</p><div class=line></div><p>Final reviewer:</p><div class=line></div></div>`}
function generateTravelerFromPlan(p){let proc=db.procedures.find(x=>x.id==p.proc)||db.procedures[0];let steps=proc?(proc.steps||[]).map(s=>({...step40(s),done:false,result:'Not Checked',initials:''})):[step40('Perform maintenance')];let j={id:nid('job'),title:'PM: '+(proc?proc.title:p.proc)+' · '+p.asset,status:'Ready for Kitting',due:p.nextDue||D(),assigned:'',asset:p.asset,proc:proc?proc.id:p.proc,procSnapshot:proc?snap40(proc):null,parts:[],tools:[],exceptions:'',closeout:'',steps};j.parts=[...new Set(j.steps.flatMap(s=>String(s.parts||'').split(/[,;\n]/).map(x=>x.trim()).filter(Boolean)))];j.tools=[...new Set(j.steps.flatMap(s=>String(s.tools||'').split(/[,;\n]/).map(x=>x.trim()).filter(Boolean)))];db.jobs.unshift(j);p.lastGenerated=D();let n=new Date(p.nextDue||D()),inc={Daily:1,Weekly:7,Monthly:30,Quarterly:90,Annual:365}[p.interval]||30;n.setDate(n.getDate()+inc);p.nextDue=n.toISOString().slice(0,10);log('PM traveler generated',j.id)}
if(!window.WF)window.WF={version:WF40_VER,modules:window.WF_MODULES||[],data:db,views,actions:{},reports:{},tests:{},print:{}};WF.version=WF40_VER;WF.production={states:STATES,gate,kit:kit40};
if(!P.includes('Control Board'))P.splice(0,0,'Control Board');
if(!P.includes('Schedule'))P.splice(P.indexOf('Control Board')+1,0,'Schedule');
if(!P.includes('PM Templates'))P.splice(P.indexOf('Procedures')+1,0,'PM Templates');
views['Control Board']=()=>card('Work Control Board',`<button class=soft onclick=newJob()>New Traveler</button><button class=ghost onclick=go('Schedule')>Schedule</button><button class=ghost onclick=csvBoard()>Board CSV</button>`,board());
views.Schedule=()=>card('Schedule',`<button class=ghost onclick=csvSchedule()>Schedule CSV</button><button class=ghost onclick=generateDueMaintenance()>Generate Due PM</button>`,schedule());
views['PM Templates']=()=>recur();
let oldDash40=views.Dashboard;views.Dashboard=()=>`<div class=grid>${m('Production States',STATES.length)}${m('Ready to Start',db.jobs.filter(j=>j.status=='Ready to Start').length)}${m('Waiting Parts',db.jobs.filter(j=>j.status=='Waiting on Parts').length)}${m('PM Templates',(db.maintenance||[]).length)}</div>${oldDash40()}`;
let oldJob40=jobView;jobView=function(j){let html=oldJob40(j);let i=db.jobs.indexOf(j);return html.replace('</p>',` <span class=pill>State ${E(j.status)}</span></p><div class=tools>${STATES.map(s=>`<button class=ghost onclick='setState(${i},"${s}")'>${s}</button>`).join('')}</div>`)};
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=ghost onclick=go('Architecture')>Architecture</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF40_VER}</b></p><p>Schema ${WF40_SCHEMA}</p><p class=muted>v4.0 adds workflow control, schedule, PM templates, production packet builder, and a WF registry foundation.</p>`);
window.quickNext=function(i){let j=db.jobs[i],n=STATES.indexOf(j.status);setState(i,STATES[Math.min(STATES.length-1,n+1)])};
window.setState=setState;
window.printProductionPacket=function(i){let j=db.jobs[i]||db.jobs[sel]||db.jobs[0],w=open('','_blank');if(!w)return alert('Allow pop-ups to print production packets.');w.document.write(`<link rel="stylesheet" href="style.css?v=4.0">${packetSections(j)}`);w.document.close();w.print&&w.print();log('Production packet printed',j.id);save()};
window.newMaintenancePlan=function(){db.maintenance=db.maintenance||[];let proc=(db.procedures[0]||{}).id||'',asset=(db.assets[0]||{}).tag||'';db.maintenance.unshift({id:'PM-'+String(db.maintenance.length+1).padStart(3,'0'),proc,asset,interval:'Monthly',nextDue:D(),lastGenerated:'',status:'Active'});save();draw()};
window.generateDueMaintenance=function(){db.maintenance=db.maintenance||[];db.maintenance.filter(p=>p.status!='Paused'&&days(p.nextDue)<=0).forEach(generateTravelerFromPlan);save();draw()};
window.csvBoard=function(){csv('workforge-control-board.csv',[['State','ID','Title','Asset','Due','Kit','Complete','Actions','Signoffs'],...db.jobs.map(j=>[j.status,j.id,j.title,j.asset,j.due,kit40(j),pct(j)+'%',reqActs(j),reqSigs(j)])])};
window.csvSchedule=function(){csv('workforge-schedule.csv',[['Due','Age','State','ID','Title','Asset','Kit','Assigned'],...db.jobs.map(j=>[j.due,days(j.due),j.status,j.id,j.title,j.asset,kit40(j),j.assigned])])};
window.csvMaintenance=function(){csv('workforge-pm-templates.csv',[['ID','Procedure','Asset','Interval','Next Due','Last Generated','Status'],...(db.maintenance||[]).map(p=>[p.id,p.proc,p.asset,p.interval,p.nextDue,p.lastGenerated,p.status])])};
let oldTest40=views['Test Harness'];views['Test Harness']=()=>{let html=oldTest40?oldTest40():'';let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('v4.0 visible',WF40_VER.includes('v4.0'),WF40_VER);pass('Control Board registered',P.includes('Control Board'),'nav');pass('Schedule registered',P.includes('Schedule'),'nav');pass('PM Templates registered',P.includes('PM Templates'),'nav');pass('WF registry available',!!window.WF,'window.WF');pass('Gate rules callable',typeof gate=='function','gate');pass('Production packet callable',typeof printProductionPacket=='function','packet');return html+card('v4.0 Production Control Checks','',tbl(['Result','Check','Detail'],rows))};
views.Diagnostics=()=>views['Test Harness']();
save=function(){db.version=WF40_VER;db.schema=WF40_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF40_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db.maintenance=db.maintenance||[];db.schema=WF40_SCHEMA;save();draw();
})();
