const WF35_VER='v3.5 Reports & Visuals',WF35_SCHEMA=350;
(function(){
function allJobs35(){return (db.jobs||[]).concat(db.archive||[])}
function today(){return new Date(D())}
function daysUntil(d){if(!d)return 0;return Math.ceil((new Date(d)-today())/86400000)}
function activeJobs(){return db.jobs||[]}
function overdueJobs(){return activeJobs().filter(j=>j.due&&daysUntil(j.due)<0&&j.status!='Complete')}
function dueSoonJobs(){return activeJobs().filter(j=>j.due&&daysUntil(j.due)>=0&&daysUntil(j.due)<=7)}
function openActions(){return (db.actions||[]).filter(a=>a.status!='Closed')}
function signoffBacklog(){return (db.signoffs||[]).filter(s=>s.status!='Signed')}
function partsReq(j){return typeof window.reqParts=='function'?window.reqParts(j):[...(j.parts||[]),...(j.steps||[]).flatMap(s=>String(s.parts||'').split(/[,;\n]/).map(x=>x.trim()).filter(Boolean))]}
function toolsReq(j){return typeof window.reqTools=='function'?window.reqTools(j):[...(j.tools||[]),...(j.steps||[]).flatMap(s=>String(s.tools||'').split(/[,;\n]/).map(x=>x.trim()).filter(Boolean))]}
function missParts(j){return typeof window.missingParts=='function'?window.missingParts(j):[]}
function missTools(j){return typeof window.missingTools=='function'?window.missingTools(j):[]}
function kitState35(j){if(typeof window.kitStatus=='function')return window.kitStatus(j);let miss=missParts(j).length+missTools(j).length,req=partsReq(j).length+toolsReq(j).length;if(!req)return'Not Checked';return miss?'Missing':'Ready'}
function assetJobs35(a){return allJobs35().filter(j=>[a.id,a.tag,a.name].filter(Boolean).includes(j.asset))}
function countBy(items,fn){let o={};items.forEach(x=>{let k=fn(x)||'Blank';o[k]=(o[k]||0)+1});return o}
function chart(title,obj){let entries=Array.isArray(obj)?obj:Object.entries(obj),max=Math.max(1,...entries.map(e=>+e[1]||0)),bars=entries.map((e,i)=>{let label=E(e[0]),v=+e[1]||0,w=Math.round(v/max*180);return`<g transform="translate(0 ${i*24})"><text x="0" y="14" font-size="11" fill="currentColor">${label}</text><rect x="82" y="3" width="${w}" height="14" rx="3" fill="currentColor" opacity=".72"/><text x="${90+w}" y="14" font-size="11" fill="currentColor">${v}</text></g>`}).join('');return`<div class=card><h3>${E(title)}</h3><svg viewBox="0 0 300 ${Math.max(42,entries.length*24+8)}" width="100%" role="img" aria-label="${E(title)}">${bars}</svg></div>`}
function reportCard(title,body,buttons=''){return card(title,buttons,body)}
function visualDashboard(){let status=countBy(activeJobs(),j=>j.status),kits=countBy(activeJobs(),kitState35),age={'Overdue':overdueJobs().length,'Due 7 Days':dueSoonJobs().length,'Later':activeJobs().filter(j=>!overdueJobs().includes(j)&&!dueSoonJobs().includes(j)).length};return`<div class=grid>${m('Open Jobs',activeJobs().length)}${m('Overdue',overdueJobs().length)}${m('Actions',openActions().length)}${m('Signoffs',signoffBacklog().length)}</div><div class=grid>${chart('Work by Status',status)}${chart('Kitting Readiness',kits)}${chart('Due Date Pressure',age)}${chart('Record Counts',{Assets:db.assets.length,Parts:db.items.filter(i=>i.kind=='Part').length,Tools:db.items.filter(i=>i.kind=='Tool').length,Labels:db.labels.length})}</div>`}
function agingTable(){return tbl(['Age','ID','Title','Status','Due','Closeout'],activeJobs().map(j=>{let d=daysUntil(j.due);return[d<0?Math.abs(d)+' days overdue':d+' days',j.id,j.title,j.status,j.due,closeout(j)]}))}
function actionTable(){return tbl(['ID','Source','Title','Owner','Due','Status'],openActions().map(a=>[a.id,a.source,a.title,a.owner,a.due,a.status]))}
function signoffTable(){return tbl(['ID','Source','Role','Reviewer','Status','Date'],signoffBacklog().map(s=>[s.id,s.source,s.role,s.reviewer,s.status,s.date]))}
function kittingGapTable(){return tbl(['Kit','ID','Title','Missing Parts','Missing Tools','Required Parts','Required Tools'],activeJobs().filter(j=>missParts(j).length||missTools(j).length).map(j=>[kitState35(j),j.id,j.title,missParts(j).join(', '),missTools(j).join(', '),partsReq(j).join(', '),toolsReq(j).join(', ')]))}
function assetSummaryTable(){return tbl(['Asset','Location','Criticality','History','Open','Failed Steps'],db.assets.map(a=>{let js=assetJobs35(a);return[a.tag,a.loc,a.criticality,js.length,js.filter(j=>db.jobs.includes(j)).length,js.reduce((n,j)=>n+fail(j),0)]}))}
function procedureUsageTable(){return tbl(['Procedure','Title','Status','Rev','Travelers'],db.procedures.map(p=>[p.id,p.title,p.status,p.rev,allJobs35().filter(j=>j.proc==p.id||(j.procSnapshot&&j.procSnapshot.id==p.id)).length]))}
function completedTable(){return tbl(['ID','Title','Asset','Status','Complete','Closeout'],(db.archive||[]).map(j=>[j.id,j.title,j.asset,j.status,pct(j)+'%',closeout(j)]))}
if(!P.includes('Visual Dashboard'))P.splice(P.indexOf('Dashboard')+1,0,'Visual Dashboard');
views['Visual Dashboard']=()=>reportCard('Visual Dashboard',visualDashboard(),`<button class=ghost onclick=printReport('Visual Dashboard')>Print</button>`);
views.Reports=()=>reportCard('Reports & Visuals',`<div class=tools><button class=ghost onclick=csvAging()>Aging CSV</button><button class=ghost onclick=csvBacklog()>Backlog CSV</button><button class=ghost onclick=csvVisualKitting()>Kitting Gaps CSV</button><button class=ghost onclick=printReport('Reports')>Print Report</button></div>${visualDashboard()}${reportCard('Aging / Due Date Report',agingTable())}${reportCard('Corrective Action Backlog',actionTable())}${reportCard('Signoff Backlog',signoffTable())}${reportCard('Kitting Gap Report',kittingGapTable())}${reportCard('Asset History Summary',assetSummaryTable())}${reportCard('Procedure Usage',procedureUsageTable())}${reportCard('Completed Work Archive',completedTable())}`,'');
let oldDash35=views.Dashboard;views.Dashboard=()=>`<div class=grid>${m('Open Jobs',activeJobs().length)}${m('Overdue',overdueJobs().length)}${m('Kit Gaps',activeJobs().filter(j=>missParts(j).length||missTools(j).length).length)}${m('Backlog',openActions().length+signoffBacklog().length)}</div>${oldDash35()}`;
let oldDiag35=views.Diagnostics;views.Diagnostics=()=>{let rows=wf35Checks(),ok=rows.filter(r=>r[0]=='PASS').length,fail=rows.length-ok;return card('Split Build Diagnostics',`<button class=soft onclick='go("Diagnostics")'>Run Diagnostics</button><button class=ghost onclick=exportJSON()>Backup JSON</button>`,`<div class=grid>${m('Checks',rows.length)}${m('Pass',ok)}${m('Fail',fail)}${m('Version','3.5')}</div>${tbl(['Result','Check','Detail'],rows)}<p class=muted>These checks validate reports, charts, aging, backlog, kitting gaps, and the split build.</p>`)};
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Diagnostics')>Open Diagnostics</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF35_VER}</b></p><p>Schema ${WF35_SCHEMA}</p><p class=muted>Reports and visual summaries are loaded from reports.js.</p>`);
window.printReport=function(name){let html=name=='Reports'?views.Reports():views['Visual Dashboard'](),w=open('','_blank');if(!w)return alert('Allow pop-ups to print reports.');w.document.write(`<link rel="stylesheet" href="style.css?v=3.5"><h1>Work Forge ${E(name)}</h1>${html}`);w.document.close();w.print&&w.print()};
window.csvAging=function(){csv('workforge-aging.csv',[['Age','ID','Title','Status','Due','Closeout'],...activeJobs().map(j=>{let d=daysUntil(j.due);return[d<0?Math.abs(d)+' days overdue':d+' days',j.id,j.title,j.status,j.due,closeout(j)]})])};
window.csvBacklog=function(){csv('workforge-backlog.csv',[['Type','ID','Source','Title','Owner/Reviewer','Due/Date','Status'],...openActions().map(a=>['Action',a.id,a.source,a.title,a.owner,a.due,a.status]),...signoffBacklog().map(s=>['Signoff',s.id,s.source,s.role,s.reviewer,s.date,s.status])])};
window.csvVisualKitting=function(){csv('workforge-kitting-gaps.csv',[['Kit','ID','Title','Missing Parts','Missing Tools','Required Parts','Required Tools'],...activeJobs().filter(j=>missParts(j).length||missTools(j).length).map(j=>[kitState35(j),j.id,j.title,missParts(j).join('; '),missTools(j).join('; '),partsReq(j).join('; '),toolsReq(j).join('; ')])])};
function wf35Checks(){let rows=[],pass=(n,ok,d='')=>rows.push([ok?'PASS':'FAIL',n,d]);pass('Version visible',WF35_VER.includes('v3.5'),WF35_VER);pass('Schema migrated',db.schema===WF35_SCHEMA,'schema '+db.schema);pass('Visual Dashboard registered',P.includes('Visual Dashboard'),'nav');pass('Charts render',chart('Test',{A:1}).includes('<svg'),'svg');pass('Aging report works',typeof agingTable()=='string','aging');pass('Backlog report works',typeof actionTable()=='string'&&typeof signoffTable()=='string','backlog');pass('Kitting gap report works',typeof kittingGapTable()=='string','kitting');pass('Asset summary works',typeof assetSummaryTable()=='string','assets');pass('Print report available',typeof printReport=='function','print');P.forEach(p=>{try{let html=views[p]();pass('Render '+p,typeof html=='string'&&html.length>0,html.length+' chars')}catch(e){pass('Render '+p,false,e.message)}});return rows}
save=function(){db.version=WF35_VER;db.schema=WF35_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF35_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db.schema=WF35_SCHEMA;save();draw();
})();
