const WF36_VER='v3.6 Full Test Harness',WF36_SCHEMA=360;
(function(){
function result(ok,name,detail=''){return[ok?'PASS':'FAIL',name,detail]}
function safe(fn){try{return[true,fn()]}catch(e){return[false,e.message||String(e)]}}
function clone(x){return JSON.parse(JSON.stringify(x))}
function allViews(){return P.filter(p=>typeof views[p]=='function')}
function clickFns(html){let names=new Set(),m;String(html).replace(/onclick=(['"])(.*?)\1/g,(a,q,body)=>{let r=/([A-Za-z_$][\w$]*)\s*\(/g;while((m=r.exec(body)))names.add(m[1])});return [...names].filter(n=>!['alert','confirm','open','print','click'].includes(n))}
function fnExists(name){try{return typeof eval(name)=='function'}catch{return typeof window[name]=='function'}}
function renderChecks(){let rows=[];rows.push(result(WF36_VER.includes('v3.6'),'Version visible',WF36_VER));rows.push(result(db.schema===WF36_SCHEMA,'Schema migrated','schema '+db.schema));rows.push(result(P.includes('Test Harness'),'Test Harness page registered','nav'));rows.push(result(!!document.querySelector('script[src*="testing.js?v=3.6"]'),'testing.js cache-busted','script tag'));rows.push(result(!!document.querySelector('script[src*="reports.js?v=3.6"]'),'reports.js cache-busted','script tag'));rows.push(result(typeof wfQrSvg=='function','QR renderer loaded','qr.js'));rows.push(result(!!$('nav')&&!!$('view')&&!!$('imp'),'Core DOM mounts exist','#nav #view #imp'));allViews().forEach(p=>{let r=safe(()=>views[p]());rows.push(result(r[0]&&typeof r[1]=='string'&&r[1].length>0,'Render '+p,r[0]?(r[1].length+' chars'):r[1]));if(r[0])clickFns(r[1]).forEach(f=>rows.push(result(fnExists(f),'Button function '+f,'from '+p)))});return rows}
function sandboxActionChecks(){let rows=[],real=clone(db),realPage=page,realSel=sel,store=localStorage.getItem(KEY);try{db=norm(sample());db=norm(db);sel=0;page='Dashboard';save();let j0=db.jobs.length,p0=db.procedures.length,l0=db.labels.length,a0=db.assets.length,i0=db.items.length;newJob();rows.push(result(db.jobs.length===j0+1,'Action: New Traveler','jobs '+db.jobs.length));newProc();rows.push(result(db.procedures.length===p0+1,'Action: New Procedure','procedures '+db.procedures.length));travelerFromProc(0);rows.push(result(!!db.jobs[0].procSnapshot,'Action: Procedure to Traveler Snapshot',db.jobs[0].procSnapshot?db.jobs[0].procSnapshot.id:''));newLabel();rows.push(result(db.labels.length>=l0+1,'Action: New Label','labels '+db.labels.length));batchLabels();rows.push(result(db.labels.length>=l0+1,'Action: Batch Labels','labels '+db.labels.length));queueAllLabels();rows.push(result(db.queue.length>0&&db.queue.every(id=>db.labels.some(l=>l.id==id)),'Action: Queue All Labels','queue '+db.queue.length));newAsset();rows.push(result(db.assets.length===a0+1,'Action: New Asset','assets '+db.assets.length));if(typeof newPart=='function'){newPart();rows.push(result(db.items.length===i0+1,'Action: New Part','items '+db.items.length))}else rows.push(result(false,'Action: New Part','missing function'));if(typeof newTool=='function'){let before=db.items.length;newTool();rows.push(result(db.items.length===before+1,'Action: New Tool','items '+db.items.length))}else rows.push(result(false,'Action: New Tool','missing function'));if(typeof holdMissingKits=='function'){holdMissingKits();rows.push(result(true,'Action: Hold Missing Kits','ran'))}else rows.push(result(false,'Action: Hold Missing Kits','missing function'));if(typeof printReport=='function')rows.push(result(true,'Action: Print Report function exists','available'));else rows.push(result(false,'Action: Print Report function exists','missing'));let exp=safe(()=>JSON.stringify(db));rows.push(result(exp[0]&&exp[1].includes('jobs'),'Action: Export JSON serializable',exp[0]?(exp[1].length+' bytes'):exp[1]));let q=safe(()=>wfQrSvg('workforge://test/HARNESS'));rows.push(result(q[0]&&q[1].includes('<svg')&&q[1].includes('<path'),'Action: QR SVG render',q[0]?'svg ok':q[1]));}catch(e){rows.push(result(false,'Sandbox action suite threw',e.message||String(e)))}finally{db=real;page=realPage;sel=realSel;if(store==null)localStorage.removeItem(KEY);else localStorage.setItem(KEY,store);save();draw()}return rows}
function dataIntegrityChecks(){let rows=[],ids={};['jobs','procedures','assets','items','labels','actions','signoffs'].forEach(k=>(db[k]||[]).forEach(o=>{if(!o.id)rows.push(result(false,'Integrity: missing ID',k));else if(ids[o.id])rows.push(result(false,'Integrity: duplicate ID',o.id));else ids[o.id]=k}));if(!rows.length)rows.push(result(true,'Integrity: unique IDs','records '+Object.keys(ids).length));rows.push(result((db.queue||[]).every(id=>db.labels.some(l=>l.id==id)),'Integrity: label queue valid',(db.queue||[]).length+' queued'));rows.push(result((db.jobs||[]).every(j=>Array.isArray(j.steps)),'Integrity: job steps arrays',db.jobs.length+' jobs'));rows.push(result((db.procedures||[]).every(p=>Array.isArray(p.steps)),'Integrity: procedure steps arrays',db.procedures.length+' procedures'));rows.push(result((db.items||[]).every(i=>i.kind&&i.name),'Integrity: items have kind/name',db.items.length+' items'));rows.push(result((db.assets||[]).every(a=>a.tag&&a.name),'Integrity: assets have tag/name',db.assets.length+' assets'));return rows}
function runHarness(){return renderChecks().concat(dataIntegrityChecks()).concat(sandboxActionChecks())}
function harnessSummary(rows){let pass=rows.filter(r=>r[0]=='PASS').length,fail=rows.length-pass;return{pass,fail,total:rows.length}}
if(!P.includes('Test Harness'))P.splice(P.indexOf('Diagnostics')+1,0,'Test Harness');
views['Test Harness']=()=>{let rows=runHarness(),s=harnessSummary(rows);return card('Full Test Harness',`<button class=soft onclick='go("Test Harness")'>Run Full Harness</button><button class=ghost onclick=csvHarness()>Harness CSV</button><button class=ghost onclick=exportJSON()>Backup JSON</button>`,`<div class=grid>${m('Checks',s.total)}${m('Pass',s.pass)}${m('Fail',s.fail)}${m('Version','3.6')}</div>${tbl(['Result','Check','Detail'],rows)}<p class=muted>The sandboxed action tests temporarily replace the in-memory project with sample data, exercise real workflow functions, then restore your saved project data.</p>`)};
let oldDiag36=views.Diagnostics;views.Diagnostics=()=>views['Test Harness']();
views.Settings=()=>card('Settings',`<button onclick=exportJSON()>Export JSON</button><button class=ghost onclick=imp.click()>Import JSON</button><button class=ghost onclick=go('Test Harness')>Run Test Harness</button><button class=bad onclick=clearStore()>Clear Local Storage</button>`,`<p><b>${WF36_VER}</b></p><p>Schema ${WF36_SCHEMA}</p><p class=muted>Use Test Harness to validate navigation, views, buttons, QR rendering, data integrity, and safe workflow actions.</p>`);
window.csvHarness=function(){let rows=runHarness();csv('workforge-test-harness.csv',[['Result','Check','Detail'],...rows])};
let oldSave36=save;save=function(){db.version=WF36_VER;db.schema=WF36_SCHEMA;localStorage.setItem(KEY,JSON.stringify(db));$('save').textContent='Autosaved '+new Date().toLocaleTimeString()};
draw=function(){$('ver').textContent=WF36_VER;$('title').textContent=page;$('nav').innerHTML=P.map((p,i)=>`<button class="${page==p?'on':''}" data-i=${i}>${E(p)}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(P[+b.dataset.i]));$('view').innerHTML=views[page]()};
db.schema=WF36_SCHEMA;save();draw();
})();
